// Pixel Art avatar catalog — mirrors DB tables:
//   avatar_style, atributo_avatar, elemento_inventario_avatar
import type { AvatarStyle, AtributoAvatar, ElementoInventarioAvatar } from '../types/avatar.types';

// ── avatar_style ──────────────────────────────────────────────────────────────
export const AVATAR_STYLES: AvatarStyle[] = [
  { id: 1, nombre: 'pixelArt' },
];

// ── atributo_avatar ───────────────────────────────────────────────────────────
export const ATRIBUTOS_AVATAR: AtributoAvatar[] = [
  { id: 1,  nombre: 'accessories',      id_avatar_style: 1 },
  { id: 2,  nombre: 'accessoriesColor', id_avatar_style: 1 },
  { id: 3,  nombre: 'beard',            id_avatar_style: 1 },
  { id: 4,  nombre: 'clothing',         id_avatar_style: 1 },
  { id: 5,  nombre: 'clothingColor',    id_avatar_style: 1 },
  { id: 6,  nombre: 'eyes',             id_avatar_style: 1 },
  { id: 7,  nombre: 'eyesColor',        id_avatar_style: 1 },
  { id: 8,  nombre: 'glasses',          id_avatar_style: 1 },
  { id: 9,  nombre: 'glassesColor',     id_avatar_style: 1 },
  { id: 10, nombre: 'hair',             id_avatar_style: 1 },
  { id: 11, nombre: 'hairColor',        id_avatar_style: 1 },
  { id: 12, nombre: 'hat',              id_avatar_style: 1 },
  { id: 13, nombre: 'hatColor',         id_avatar_style: 1 },
  { id: 14, nombre: 'mouth',            id_avatar_style: 1 },
  { id: 15, nombre: 'mouthColor',       id_avatar_style: 1 },
  { id: 16, nombre: 'backgroundColor',        id_avatar_style: 1 },
  { id: 17, nombre: 'backgroundType',         id_avatar_style: 1 },
  { id: 18, nombre: 'skinColor',              id_avatar_style: 1 },
  { id: 19, nombre: 'accessoriesProbability', id_avatar_style: 1 },
  { id: 20, nombre: 'beardProbability',       id_avatar_style: 1 },
  { id: 21, nombre: 'glassesProbability',     id_avatar_style: 1 },
  { id: 22, nombre: 'hatProbability',         id_avatar_style: 1 },
];

// ── elemento_inventario_avatar ────────────────────────────────────────────────
export const ELEMENTOS_INVENTARIO: ElementoInventarioAvatar[] = [
  // accessories (id_atributo_avatar: 1)
  { id: 1,  nombre: 'variant01', id_atributo_avatar: 1 },
  { id: 2,  nombre: 'variant02', id_atributo_avatar: 1 },
  { id: 3,  nombre: 'variant03', id_atributo_avatar: 1 },
  { id: 4,  nombre: 'variant04', id_atributo_avatar: 1 },

  // accessoriesColor (id_atributo_avatar: 2)
  { id: 5,  nombre: 'a9a9a9',    id_atributo_avatar: 2 },
  { id: 6,  nombre: 'd3d3d3',    id_atributo_avatar: 2 },
  { id: 7,  nombre: 'daa520',    id_atributo_avatar: 2 },
  { id: 8,  nombre: 'fafad2',    id_atributo_avatar: 2 },
  { id: 9,  nombre: 'ffd700',    id_atributo_avatar: 2 },
  { id: 10, nombre: 'transparent', id_atributo_avatar: 2 },

  // beard (id_atributo_avatar: 3)
  { id: 11, nombre: 'variant01', id_atributo_avatar: 3 },
  { id: 12, nombre: 'variant02', id_atributo_avatar: 3 },
  { id: 13, nombre: 'variant03', id_atributo_avatar: 3 },
  { id: 14, nombre: 'variant04', id_atributo_avatar: 3 },
  { id: 15, nombre: 'variant05', id_atributo_avatar: 3 },
  { id: 16, nombre: 'variant06', id_atributo_avatar: 3 },
  { id: 17, nombre: 'variant07', id_atributo_avatar: 3 },
  { id: 18, nombre: 'variant08', id_atributo_avatar: 3 },

  // clothing (id_atributo_avatar: 4)
  { id: 19, nombre: 'variant01', id_atributo_avatar: 4 },
  { id: 20, nombre: 'variant02', id_atributo_avatar: 4 },
  { id: 21, nombre: 'variant03', id_atributo_avatar: 4 },
  { id: 22, nombre: 'variant04', id_atributo_avatar: 4 },
  { id: 23, nombre: 'variant05', id_atributo_avatar: 4 },
  { id: 24, nombre: 'variant06', id_atributo_avatar: 4 },
  { id: 25, nombre: 'variant07', id_atributo_avatar: 4 },
  { id: 26, nombre: 'variant08', id_atributo_avatar: 4 },
  { id: 27, nombre: 'variant09', id_atributo_avatar: 4 },
  { id: 28, nombre: 'variant10', id_atributo_avatar: 4 },
  { id: 29, nombre: 'variant11', id_atributo_avatar: 4 },
  { id: 30, nombre: 'variant12', id_atributo_avatar: 4 },
  { id: 31, nombre: 'variant13', id_atributo_avatar: 4 },
  { id: 32, nombre: 'variant14', id_atributo_avatar: 4 },
  { id: 33, nombre: 'variant15', id_atributo_avatar: 4 },
  { id: 34, nombre: 'variant16', id_atributo_avatar: 4 },
  { id: 35, nombre: 'variant17', id_atributo_avatar: 4 },
  { id: 36, nombre: 'variant18', id_atributo_avatar: 4 },
  { id: 37, nombre: 'variant19', id_atributo_avatar: 4 },
  { id: 38, nombre: 'variant20', id_atributo_avatar: 4 },
  { id: 39, nombre: 'variant21', id_atributo_avatar: 4 },
  { id: 40, nombre: 'variant22', id_atributo_avatar: 4 },
  { id: 41, nombre: 'variant23', id_atributo_avatar: 4 },

  // clothingColor (id_atributo_avatar: 5)
  { id: 42, nombre: '00b159',    id_atributo_avatar: 5 },
  { id: 43, nombre: '03396c',    id_atributo_avatar: 5 },
  { id: 44, nombre: '428bca',    id_atributo_avatar: 5 },
  { id: 45, nombre: '44c585',    id_atributo_avatar: 5 },
  { id: 46, nombre: '5bc0de',    id_atributo_avatar: 5 },
  { id: 47, nombre: '88d8b0',    id_atributo_avatar: 5 },
  { id: 48, nombre: 'ae0001',    id_atributo_avatar: 5 },
  { id: 49, nombre: 'd11141',    id_atributo_avatar: 5 },
  { id: 50, nombre: 'ff6f69',    id_atributo_avatar: 5 },
  { id: 51, nombre: 'ffc425',    id_atributo_avatar: 5 },
  { id: 52, nombre: 'ffd969',    id_atributo_avatar: 5 },
  { id: 53, nombre: 'ffeead',    id_atributo_avatar: 5 },
  { id: 54, nombre: 'transparent', id_atributo_avatar: 5 },

  // eyes (id_atributo_avatar: 6)
  { id: 55, nombre: 'variant01', id_atributo_avatar: 6 },
  { id: 56, nombre: 'variant02', id_atributo_avatar: 6 },
  { id: 57, nombre: 'variant03', id_atributo_avatar: 6 },
  { id: 58, nombre: 'variant04', id_atributo_avatar: 6 },
  { id: 59, nombre: 'variant05', id_atributo_avatar: 6 },
  { id: 60, nombre: 'variant06', id_atributo_avatar: 6 },
  { id: 61, nombre: 'variant07', id_atributo_avatar: 6 },
  { id: 62, nombre: 'variant08', id_atributo_avatar: 6 },
  { id: 63, nombre: 'variant09', id_atributo_avatar: 6 },
  { id: 64, nombre: 'variant10', id_atributo_avatar: 6 },
  { id: 65, nombre: 'variant11', id_atributo_avatar: 6 },
  { id: 66, nombre: 'variant12', id_atributo_avatar: 6 },

  // eyesColor (id_atributo_avatar: 7)
  { id: 67, nombre: '588387',    id_atributo_avatar: 7 },
  { id: 68, nombre: '5b7c8b',    id_atributo_avatar: 7 },
  { id: 69, nombre: '647b90',    id_atributo_avatar: 7 },
  { id: 70, nombre: '697b94',    id_atributo_avatar: 7 },
  { id: 71, nombre: '76778b',    id_atributo_avatar: 7 },
  { id: 72, nombre: '876658',    id_atributo_avatar: 7 },
  { id: 73, nombre: 'transparent', id_atributo_avatar: 7 },

  // glasses (id_atributo_avatar: 8)
  { id: 74, nombre: 'dark01',    id_atributo_avatar: 8 },
  { id: 75, nombre: 'dark02',    id_atributo_avatar: 8 },
  { id: 76, nombre: 'dark03',    id_atributo_avatar: 8 },
  { id: 77, nombre: 'dark04',    id_atributo_avatar: 8 },
  { id: 78, nombre: 'dark05',    id_atributo_avatar: 8 },
  { id: 79, nombre: 'dark06',    id_atributo_avatar: 8 },
  { id: 80, nombre: 'dark07',    id_atributo_avatar: 8 },
  { id: 81, nombre: 'light01',   id_atributo_avatar: 8 },
  { id: 82, nombre: 'light02',   id_atributo_avatar: 8 },
  { id: 83, nombre: 'light03',   id_atributo_avatar: 8 },
  { id: 84, nombre: 'light04',   id_atributo_avatar: 8 },
  { id: 85, nombre: 'light05',   id_atributo_avatar: 8 },
  { id: 86, nombre: 'light06',   id_atributo_avatar: 8 },
  { id: 87, nombre: 'light07',   id_atributo_avatar: 8 },

  // glassesColor (id_atributo_avatar: 9)
  { id: 88, nombre: '191919',    id_atributo_avatar: 9 },
  { id: 89, nombre: '323232',    id_atributo_avatar: 9 },
  { id: 90, nombre: '43677d',    id_atributo_avatar: 9 },
  { id: 91, nombre: '4b4b4b',    id_atributo_avatar: 9 },
  { id: 92, nombre: '5f705c',    id_atributo_avatar: 9 },
  { id: 93, nombre: 'a04b5d',    id_atributo_avatar: 9 },
  { id: 94, nombre: 'transparent', id_atributo_avatar: 9 },

  // hair (id_atributo_avatar: 10)
  { id: 95,  nombre: 'long01',   id_atributo_avatar: 10 },
  { id: 96,  nombre: 'long02',   id_atributo_avatar: 10 },
  { id: 97,  nombre: 'long03',   id_atributo_avatar: 10 },
  { id: 98,  nombre: 'long04',   id_atributo_avatar: 10 },
  { id: 99,  nombre: 'long05',   id_atributo_avatar: 10 },
  { id: 100, nombre: 'long06',   id_atributo_avatar: 10 },
  { id: 101, nombre: 'long07',   id_atributo_avatar: 10 },
  { id: 102, nombre: 'long08',   id_atributo_avatar: 10 },
  { id: 103, nombre: 'long09',   id_atributo_avatar: 10 },
  { id: 104, nombre: 'long10',   id_atributo_avatar: 10 },
  { id: 105, nombre: 'long11',   id_atributo_avatar: 10 },
  { id: 106, nombre: 'long12',   id_atributo_avatar: 10 },
  { id: 107, nombre: 'long13',   id_atributo_avatar: 10 },
  { id: 108, nombre: 'long14',   id_atributo_avatar: 10 },
  { id: 109, nombre: 'long15',   id_atributo_avatar: 10 },
  { id: 110, nombre: 'long16',   id_atributo_avatar: 10 },
  { id: 111, nombre: 'long17',   id_atributo_avatar: 10 },
  { id: 112, nombre: 'long18',   id_atributo_avatar: 10 },
  { id: 113, nombre: 'long19',   id_atributo_avatar: 10 },
  { id: 114, nombre: 'long20',   id_atributo_avatar: 10 },
  { id: 115, nombre: 'long21',   id_atributo_avatar: 10 },
  { id: 116, nombre: 'short01',  id_atributo_avatar: 10 },
  { id: 117, nombre: 'short02',  id_atributo_avatar: 10 },
  { id: 118, nombre: 'short03',  id_atributo_avatar: 10 },
  { id: 119, nombre: 'short04',  id_atributo_avatar: 10 },
  { id: 120, nombre: 'short05',  id_atributo_avatar: 10 },
  { id: 121, nombre: 'short06',  id_atributo_avatar: 10 },
  { id: 122, nombre: 'short07',  id_atributo_avatar: 10 },
  { id: 123, nombre: 'short08',  id_atributo_avatar: 10 },
  { id: 124, nombre: 'short09',  id_atributo_avatar: 10 },
  { id: 125, nombre: 'short10',  id_atributo_avatar: 10 },
  { id: 126, nombre: 'short11',  id_atributo_avatar: 10 },
  { id: 127, nombre: 'short12',  id_atributo_avatar: 10 },
  { id: 128, nombre: 'short13',  id_atributo_avatar: 10 },
  { id: 129, nombre: 'short14',  id_atributo_avatar: 10 },
  { id: 130, nombre: 'short15',  id_atributo_avatar: 10 },
  { id: 131, nombre: 'short16',  id_atributo_avatar: 10 },
  { id: 132, nombre: 'short17',  id_atributo_avatar: 10 },
  { id: 133, nombre: 'short18',  id_atributo_avatar: 10 },
  { id: 134, nombre: 'short19',  id_atributo_avatar: 10 },
  { id: 135, nombre: 'short20',  id_atributo_avatar: 10 },
  { id: 136, nombre: 'short21',  id_atributo_avatar: 10 },
  { id: 137, nombre: 'short22',  id_atributo_avatar: 10 },
  { id: 138, nombre: 'short23',  id_atributo_avatar: 10 },
  { id: 139, nombre: 'short24',  id_atributo_avatar: 10 },

  // hairColor (id_atributo_avatar: 11)
  { id: 140, nombre: '009bbd',   id_atributo_avatar: 11 },
  { id: 141, nombre: '28150a',   id_atributo_avatar: 11 },
  { id: 142, nombre: '603015',   id_atributo_avatar: 11 },
  { id: 143, nombre: '603a14',   id_atributo_avatar: 11 },
  { id: 144, nombre: '611c17',   id_atributo_avatar: 11 },
  { id: 145, nombre: '612616',   id_atributo_avatar: 11 },
  { id: 146, nombre: '83623b',   id_atributo_avatar: 11 },
  { id: 147, nombre: '91cb15',   id_atributo_avatar: 11 },
  { id: 148, nombre: 'a78961',   id_atributo_avatar: 11 },
  { id: 149, nombre: 'bd1700',   id_atributo_avatar: 11 },
  { id: 150, nombre: 'cab188',   id_atributo_avatar: 11 },
  { id: 151, nombre: 'transparent', id_atributo_avatar: 11 },

  // hat (id_atributo_avatar: 12)
  { id: 152, nombre: 'variant01', id_atributo_avatar: 12 },
  { id: 153, nombre: 'variant02', id_atributo_avatar: 12 },
  { id: 154, nombre: 'variant03', id_atributo_avatar: 12 },
  { id: 155, nombre: 'variant04', id_atributo_avatar: 12 },
  { id: 156, nombre: 'variant05', id_atributo_avatar: 12 },
  { id: 157, nombre: 'variant06', id_atributo_avatar: 12 },
  { id: 158, nombre: 'variant07', id_atributo_avatar: 12 },
  { id: 159, nombre: 'variant08', id_atributo_avatar: 12 },
  { id: 160, nombre: 'variant09', id_atributo_avatar: 12 },
  { id: 161, nombre: 'variant10', id_atributo_avatar: 12 },

  // hatColor (id_atributo_avatar: 13)
  { id: 162, nombre: '2663a3',   id_atributo_avatar: 13 },
  { id: 163, nombre: '2e1e05',   id_atributo_avatar: 13 },
  { id: 164, nombre: '3d8a6b',   id_atributo_avatar: 13 },
  { id: 165, nombre: '614f8a',   id_atributo_avatar: 13 },
  { id: 166, nombre: '989789',   id_atributo_avatar: 13 },
  { id: 167, nombre: 'a62116',   id_atributo_avatar: 13 },
  { id: 168, nombre: 'cc6192',   id_atributo_avatar: 13 },
  { id: 169, nombre: 'transparent', id_atributo_avatar: 13 },

  // mouth (id_atributo_avatar: 14)
  { id: 170, nombre: 'happy01',  id_atributo_avatar: 14 },
  { id: 171, nombre: 'happy02',  id_atributo_avatar: 14 },
  { id: 172, nombre: 'happy03',  id_atributo_avatar: 14 },
  { id: 173, nombre: 'happy04',  id_atributo_avatar: 14 },
  { id: 174, nombre: 'happy05',  id_atributo_avatar: 14 },
  { id: 175, nombre: 'happy06',  id_atributo_avatar: 14 },
  { id: 176, nombre: 'happy07',  id_atributo_avatar: 14 },
  { id: 177, nombre: 'happy08',  id_atributo_avatar: 14 },
  { id: 178, nombre: 'happy09',  id_atributo_avatar: 14 },
  { id: 179, nombre: 'happy10',  id_atributo_avatar: 14 },
  { id: 180, nombre: 'happy11',  id_atributo_avatar: 14 },
  { id: 181, nombre: 'happy12',  id_atributo_avatar: 14 },
  { id: 182, nombre: 'happy13',  id_atributo_avatar: 14 },
  { id: 183, nombre: 'sad01',    id_atributo_avatar: 14 },
  { id: 184, nombre: 'sad02',    id_atributo_avatar: 14 },
  { id: 185, nombre: 'sad03',    id_atributo_avatar: 14 },
  { id: 186, nombre: 'sad04',    id_atributo_avatar: 14 },
  { id: 187, nombre: 'sad05',    id_atributo_avatar: 14 },
  { id: 188, nombre: 'sad06',    id_atributo_avatar: 14 },
  { id: 189, nombre: 'sad07',    id_atributo_avatar: 14 },
  { id: 190, nombre: 'sad08',    id_atributo_avatar: 14 },
  { id: 191, nombre: 'sad09',    id_atributo_avatar: 14 },
  { id: 192, nombre: 'sad10',    id_atributo_avatar: 14 },

  // mouthColor (id_atributo_avatar: 15)
  { id: 193, nombre: 'c98276',   id_atributo_avatar: 15 },
  { id: 194, nombre: 'd29985',   id_atributo_avatar: 15 },
  { id: 195, nombre: 'de0f0d',   id_atributo_avatar: 15 },
  { id: 196, nombre: 'e35d6a',   id_atributo_avatar: 15 },
  { id: 197, nombre: 'transparent', id_atributo_avatar: 15 },

  // backgroundColor (id_atributo_avatar: 16)
  { id: 198, nombre: 'b6e3f4',   id_atributo_avatar: 16 },
  { id: 199, nombre: 'c0aede',   id_atributo_avatar: 16 },
  { id: 200, nombre: 'd1d4f9',   id_atributo_avatar: 16 },
  { id: 201, nombre: 'ffd5dc',   id_atributo_avatar: 16 },
  { id: 202, nombre: 'ffdfbf',   id_atributo_avatar: 16 },
  { id: 203, nombre: 'transparent', id_atributo_avatar: 16 },

  // backgroundType (id_atributo_avatar: 17)
  { id: 204, nombre: 'solid',          id_atributo_avatar: 17 },
  { id: 205, nombre: 'gradientLinear', id_atributo_avatar: 17 },

  // skinColor (id_atributo_avatar: 18)
  { id: 206, nombre: '8d5524',   id_atributo_avatar: 18 },
  { id: 207, nombre: 'a26d3d',   id_atributo_avatar: 18 },
  { id: 208, nombre: 'b68655',   id_atributo_avatar: 18 },
  { id: 209, nombre: 'cb9e6e',   id_atributo_avatar: 18 },
  { id: 210, nombre: 'e0b687',   id_atributo_avatar: 18 },
  { id: 211, nombre: 'eac393',   id_atributo_avatar: 18 },
  { id: 212, nombre: 'f5cfa0',   id_atributo_avatar: 18 },
  { id: 213, nombre: 'ffdbac',   id_atributo_avatar: 18 },
  { id: 214, nombre: 'transparent', id_atributo_avatar: 18 },
];
