import type { Project } from '@/features/projects/types/Project';

const MOCK_PROJECTS: Project[] = [
  {
    id: 1,
    nombre: 'Proyecto Alpha',
    descripcion: 'Migración completa del sistema legacy a arquitectura moderna con React y Supabase.',
    cliente: 'Mahindra',
    fecha_inicial: '2025-09-01',
    fecha_final: '2026-03-01',
    fecha_creacion: '2025-08-15',
    dependencia_externa: false,
    hitos_estimados: 8,
    fte: 3,
    presupuesto: 500000,
    costo_mensual: 80000,
    tolerancia_desviacion: 0.1,
    peso_presupuesto: 0.5,
    peso_retraso: 0.5,
    id_divisa_presupuesto: 1,
    id_divisa_costo: 1,
    id_modelo_facturacion: 1,
    id_complejidad: 2,
    id_tipo: 1,
    id_estatus: 1,
    id_metodologia: 1,
    id_creador: 101,
  },
  {
    id: 2,
    nombre: 'Proyecto Beta',
    descripcion: 'Desarrollo del módulo de reportes financieros con exportación a PDF y Excel.',
    cliente: 'Cliente B',
    fecha_inicial: '2025-11-01',
    fecha_final: '2026-05-15',
    fecha_creacion: '2025-10-20',
    dependencia_externa: false,
    hitos_estimados: 6,
    fte: 5,
    presupuesto: 750000,
    costo_mensual: 120000,
    tolerancia_desviacion: 0.15,
    peso_presupuesto: 0.6,
    peso_retraso: 0.4,
    id_divisa_presupuesto: 1,
    id_divisa_costo: 1,
    id_modelo_facturacion: 2,
    id_complejidad: 3,
    id_tipo: 2,
    id_estatus: 2,
    id_metodologia: 2,
    id_creador: 102,
  },
  {
    id: 3,
    nombre: 'Proyecto Gamma',
    descripcion: 'Integración con API de pagos externos. Bloqueado por dependencia de proveedor.',
    cliente: 'Cliente C',
    fecha_inicial: '2025-12-01',
    fecha_final: '2026-04-10',
    fecha_creacion: '2025-11-15',
    dependencia_externa: true,
    hitos_estimados: 4,
    fte: 2,
    presupuesto: 300000,
    costo_mensual: 60000,
    tolerancia_desviacion: 0.2,
    peso_presupuesto: 0.4,
    peso_retraso: 0.6,
    id_divisa_presupuesto: 2,
    id_divisa_costo: 2,
    id_modelo_facturacion: 1,
    id_complejidad: 2,
    id_tipo: 3,
    id_estatus: 3,
    id_metodologia: 1,
    id_creador: 101,
  },
  {
    id: 4,
    nombre: 'Proyecto Delta',
    descripcion: 'App móvil para gestión de inventario en campo. Pendiente de asignación de equipo.',
    cliente: 'Cliente D',
    fecha_inicial: '2026-03-01',
    fecha_final: '2026-08-01',
    fecha_creacion: '2026-02-10',
    dependencia_externa: false,
    hitos_estimados: 5,
    fte: 0,
    presupuesto: 200000,
    costo_mensual: 0,
    tolerancia_desviacion: 0.1,
    peso_presupuesto: 0.5,
    peso_retraso: 0.5,
    id_divisa_presupuesto: 1,
    id_divisa_costo: 1,
    id_modelo_facturacion: 3,
    id_complejidad: 1,
    id_tipo: 2,
    id_estatus: 4,
    id_metodologia: 3,
    id_creador: 103,
  },
];

// TODO: reemplazar con llamada real a la API cuando esté lista
export const fetchProjects = (): Promise<Project[]> =>
  new Promise((resolve) => setTimeout(() => resolve(MOCK_PROJECTS), 800));
