CREATE TABLE public.estatus_backlog_item_personalizado (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL,
  orden SMALLINT NOT NULL,
  id_proyecto INT NOT NULL,
  CONSTRAINT estatus_backlog_item_personalizado_id_proyecto_fkey
    FOREIGN KEY (id_proyecto)
    REFERENCES public.proyecto(id)
    ON DELETE CASCADE
);