BEGIN;

-- Catálogos base del sistema de notificaciones
CREATE TABLE IF NOT EXISTS public.catalogo_tipo_notificacion (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo character varying(50) NOT NULL UNIQUE,
  nombre character varying(80) NOT NULL,
  descripcion character varying(250),
  activo boolean DEFAULT true NOT NULL
);

CREATE TABLE IF NOT EXISTS public.catalogo_seccion_proyecto_notificacion (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo character varying(50) NOT NULL UNIQUE,
  nombre character varying(80) NOT NULL,
  ruta_relativa character varying(100) NOT NULL,
  activo boolean DEFAULT true NOT NULL
);

-- Tipos con identificadores estables porque algunas tablas detalle usan columnas generadas
DO $$
DECLARE
  v_seq text;
BEGIN
  UPDATE public.catalogo_tipo_notificacion
  SET codigo = LEFT(codigo::text, 35) || '_legacy_' || id::text,
      activo = false
  WHERE codigo = 'sistema' AND id <> 1;

  UPDATE public.catalogo_tipo_notificacion
  SET codigo = LEFT(codigo::text, 35) || '_legacy_' || id::text,
      activo = false
  WHERE codigo = 'invitacion_proyecto' AND id <> 2;

  UPDATE public.catalogo_tipo_notificacion
  SET codigo = LEFT(codigo::text, 35) || '_legacy_' || id::text,
      activo = false
  WHERE codigo = 'sugerencia_creacion_backlog_item' AND id <> 3;

  UPDATE public.catalogo_tipo_notificacion
  SET codigo = LEFT(codigo::text, 35) || '_legacy_' || id::text,
      activo = false
  WHERE codigo = 'cambio_proyecto' AND id <> 4;

  UPDATE public.catalogo_tipo_notificacion
  SET codigo = LEFT(codigo::text, 35) || '_legacy_' || id::text,
      activo = false
  WHERE codigo = 'backlog_item_proximo_vencer' AND id <> 5;

  UPDATE public.catalogo_tipo_notificacion
  SET codigo = LEFT(codigo::text, 35) || '_legacy_' || id::text,
      activo = false
  WHERE codigo = 'cambio_backlog_item' AND id <> 6;

  UPDATE public.catalogo_tipo_notificacion
  SET codigo = LEFT(codigo::text, 35) || '_legacy_' || id::text,
      activo = false
  WHERE codigo = 'creacion_backlog_item' AND id <> 7;

  UPDATE public.catalogo_tipo_notificacion
  SET codigo = LEFT(codigo::text, 35) || '_legacy_' || id::text,
      activo = false
  WHERE codigo = 'sprint_proximo_vencer' AND id <> 8;

  INSERT INTO public.catalogo_tipo_notificacion (id, codigo, nombre, descripcion, activo)
  VALUES
    (1, 'sistema', 'Sistema', 'Notificación genérica sin referencia adicional.', true),
    (2, 'invitacion_proyecto', 'Invitación de proyecto', 'Invitación enviada a un usuario para integrarse a un proyecto.', true),
    (3, 'sugerencia_creacion_backlog_item', 'Sugerencia de creación de backlog item', 'Sugerencia de creación de backlog item dirigida a PM del proyecto.', true),
    (4, 'cambio_proyecto', 'Cambio de proyecto', 'Cambio relevante en la información general del proyecto.', true),
    (5, 'backlog_item_proximo_vencer', 'Backlog item próximo a vencer', 'Backlog item con fecha de vencimiento próxima.', true),
    (6, 'cambio_backlog_item', 'Cambio de backlog item', 'Cambio relevante en un backlog item.', true),
    (7, 'creacion_backlog_item', 'Creación de backlog item', 'Backlog item creado con responsable asignado.', true),
    (8, 'sprint_proximo_vencer', 'Sprint próximo a finalizar', 'Sprint con fecha final próxima.', true)
  ON CONFLICT (id) DO UPDATE
  SET codigo = EXCLUDED.codigo,
      nombre = EXCLUDED.nombre,
      descripcion = EXCLUDED.descripcion,
      activo = EXCLUDED.activo;

  v_seq := pg_get_serial_sequence('public.catalogo_tipo_notificacion', 'id');
  IF v_seq IS NOT NULL THEN
    PERFORM setval(v_seq, GREATEST((SELECT COALESCE(MAX(id), 1) FROM public.catalogo_tipo_notificacion), 1), true);
  END IF;
END $$;

INSERT INTO public.catalogo_seccion_proyecto_notificacion (codigo, nombre, ruta_relativa, activo)
VALUES
  ('general', 'General', 'general', true),
  ('backlog', 'Backlog', 'backlog', true),
  ('sprints', 'Sprints', 'sprints', true),
  ('equipo', 'Equipo', 'equipo', true)
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre,
    ruta_relativa = EXCLUDED.ruta_relativa,
    activo = EXCLUDED.activo;

-- Tabla principal de notificaciones
CREATE TABLE IF NOT EXISTS public.notificacion (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre character varying(50) NOT NULL,
  descripcion character varying(100),
  leida boolean DEFAULT false NOT NULL,
  fecha_lectura timestamp with time zone,
  id_usuario integer NOT NULL,
  fecha_envio timestamp with time zone DEFAULT now() NOT NULL,
  id_tipo_notificacion smallint DEFAULT 1 NOT NULL
);

ALTER TABLE public.notificacion ADD COLUMN IF NOT EXISTS id_tipo_notificacion smallint;
ALTER TABLE public.notificacion ALTER COLUMN id_tipo_notificacion SET DEFAULT 1;

UPDATE public.notificacion n
SET id_tipo_notificacion = 1
WHERE n.id_tipo_notificacion IS NULL;

UPDATE public.notificacion n
SET id_tipo_notificacion = 1
WHERE NOT EXISTS (
  SELECT 1
  FROM public.catalogo_tipo_notificacion c
  WHERE c.id = n.id_tipo_notificacion
);

-- Normalización de tipos para detalles existentes antes de reforzar llaves compuestas
DO $$
BEGIN
  IF to_regclass('public.notificacion_invitacion_proyecto') IS NOT NULL THEN
    UPDATE public.notificacion n
    SET id_tipo_notificacion = 2
    FROM public.notificacion_invitacion_proyecto d
    WHERE d.id_notificacion = n.id;
  END IF;

  IF to_regclass('public.notificacion_backlog_item_sugerencia') IS NOT NULL THEN
    UPDATE public.notificacion n
    SET id_tipo_notificacion = 3
    FROM public.notificacion_backlog_item_sugerencia d
    WHERE d.id_notificacion = n.id;
  END IF;

  IF to_regclass('public.notificacion_proyecto') IS NOT NULL THEN
    UPDATE public.notificacion n
    SET id_tipo_notificacion = 4
    FROM public.notificacion_proyecto d
    WHERE d.id_notificacion = n.id;
  END IF;

  IF to_regclass('public.notificacion_backlog_item_vencimiento') IS NOT NULL THEN
    UPDATE public.notificacion n
    SET id_tipo_notificacion = 5
    FROM public.notificacion_backlog_item_vencimiento d
    WHERE d.id_notificacion = n.id;
  END IF;
END $$;

ALTER TABLE public.notificacion ALTER COLUMN id_tipo_notificacion SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'notificacion_id_id_tipo_notificacion_key'
      AND conrelid = 'public.notificacion'::regclass
  ) THEN
    ALTER TABLE public.notificacion
      ADD CONSTRAINT notificacion_id_id_tipo_notificacion_key UNIQUE (id, id_tipo_notificacion);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'notificacion_leida_fecha_check'
      AND conrelid = 'public.notificacion'::regclass
  ) THEN
    ALTER TABLE public.notificacion
      ADD CONSTRAINT notificacion_leida_fecha_check
      CHECK (
        (leida = false AND fecha_lectura IS NULL)
        OR
        (leida = true AND fecha_lectura IS NOT NULL)
      ) NOT VALID;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'notificacion_id_tipo_notificacion_fkey'
      AND conrelid = 'public.notificacion'::regclass
  ) THEN
    ALTER TABLE public.notificacion
      ADD CONSTRAINT notificacion_id_tipo_notificacion_fkey
      FOREIGN KEY (id_tipo_notificacion)
      REFERENCES public.catalogo_tipo_notificacion(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'notificacion_id_usuario_fkey'
      AND conrelid = 'public.notificacion'::regclass
  ) THEN
    ALTER TABLE public.notificacion
      ADD CONSTRAINT notificacion_id_usuario_fkey
      FOREIGN KEY (id_usuario)
      REFERENCES public.usuario(id)
      DEFERRABLE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'backlog_item_id_id_proyecto_key'
      AND conrelid = 'public.backlog_item'::regclass
  ) THEN
    ALTER TABLE public.backlog_item
      ADD CONSTRAINT backlog_item_id_id_proyecto_key UNIQUE (id, id_proyecto);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'sprint_id_id_proyecto_key'
      AND conrelid = 'public.sprint'::regclass
  ) THEN
    ALTER TABLE public.sprint
      ADD CONSTRAINT sprint_id_id_proyecto_key UNIQUE (id, id_proyecto);
  END IF;
END $$;

-- Tablas detalle con foreign keys reales por tipo de notificación
CREATE TABLE IF NOT EXISTS public.notificacion_invitacion_proyecto (
  id_notificacion integer NOT NULL PRIMARY KEY,
  id_tipo_notificacion smallint GENERATED ALWAYS AS (2::smallint) STORED,
  id_invitacion_proyecto integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.notificacion_proyecto (
  id_notificacion integer NOT NULL PRIMARY KEY,
  id_tipo_notificacion smallint GENERATED ALWAYS AS (4::smallint) STORED,
  id_proyecto integer NOT NULL,
  id_seccion_proyecto smallint NOT NULL,
  id_usuario_actor integer
);

CREATE TABLE IF NOT EXISTS public.notificacion_backlog_item_sugerencia (
  id_notificacion integer NOT NULL PRIMARY KEY,
  id_tipo_notificacion smallint GENERATED ALWAYS AS (3::smallint) STORED,
  id_backlog_item bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.notificacion_backlog_item_vencimiento (
  id_notificacion integer NOT NULL PRIMARY KEY,
  id_tipo_notificacion smallint GENERATED ALWAYS AS (5::smallint) STORED,
  id_backlog_item bigint NOT NULL,
  id_proyecto integer NOT NULL,
  fecha_vencimiento_notificada timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.notificacion_backlog_item_cambio (
  id_notificacion integer NOT NULL PRIMARY KEY,
  id_tipo_notificacion smallint GENERATED ALWAYS AS (6::smallint) STORED,
  id_backlog_item bigint NOT NULL,
  id_proyecto integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.notificacion_backlog_item_creacion (
  id_notificacion integer NOT NULL PRIMARY KEY,
  id_tipo_notificacion smallint GENERATED ALWAYS AS (7::smallint) STORED,
  id_backlog_item bigint NOT NULL,
  id_proyecto integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.notificacion_sprint_vencimiento (
  id_notificacion integer NOT NULL PRIMARY KEY,
  id_tipo_notificacion smallint GENERATED ALWAYS AS (8::smallint) STORED,
  id_sprint bigint NOT NULL,
  id_proyecto integer NOT NULL,
  fecha_final_notificada timestamp with time zone NOT NULL
);

-- Registros de vencimiento para no repetir notificaciones temporales
CREATE TABLE IF NOT EXISTS public.notificacion_backlog_item_vencimiento_registro (
  id_usuario integer NOT NULL,
  id_backlog_item bigint NOT NULL,
  fecha_vencimiento_notificada timestamp with time zone NOT NULL,
  id_notificacion integer,
  fecha_registro timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id_usuario, id_backlog_item, fecha_vencimiento_notificada)
);

CREATE TABLE IF NOT EXISTS public.notificacion_sprint_vencimiento_registro (
  id_usuario integer NOT NULL,
  id_sprint bigint NOT NULL,
  fecha_final_notificada timestamp with time zone NOT NULL,
  id_notificacion integer,
  fecha_registro timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (id_usuario, id_sprint, fecha_final_notificada)
);

-- Constraints de tablas detalle y registros
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_invitacion_proyecto_tipo_fkey' AND conrelid = 'public.notificacion_invitacion_proyecto'::regclass) THEN
    ALTER TABLE public.notificacion_invitacion_proyecto
      ADD CONSTRAINT notificacion_invitacion_proyecto_tipo_fkey
      FOREIGN KEY (id_notificacion, id_tipo_notificacion)
      REFERENCES public.notificacion(id, id_tipo_notificacion)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_invitacion_proyecto_invitacion_fkey' AND conrelid = 'public.notificacion_invitacion_proyecto'::regclass) THEN
    ALTER TABLE public.notificacion_invitacion_proyecto
      ADD CONSTRAINT notificacion_invitacion_proyecto_invitacion_fkey
      FOREIGN KEY (id_invitacion_proyecto)
      REFERENCES public.invitacion_proyecto(id)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_proyecto_tipo_fkey' AND conrelid = 'public.notificacion_proyecto'::regclass) THEN
    ALTER TABLE public.notificacion_proyecto
      ADD CONSTRAINT notificacion_proyecto_tipo_fkey
      FOREIGN KEY (id_notificacion, id_tipo_notificacion)
      REFERENCES public.notificacion(id, id_tipo_notificacion)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_proyecto_proyecto_fkey' AND conrelid = 'public.notificacion_proyecto'::regclass) THEN
    ALTER TABLE public.notificacion_proyecto
      ADD CONSTRAINT notificacion_proyecto_proyecto_fkey
      FOREIGN KEY (id_proyecto)
      REFERENCES public.proyecto(id)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_proyecto_seccion_fkey' AND conrelid = 'public.notificacion_proyecto'::regclass) THEN
    ALTER TABLE public.notificacion_proyecto
      ADD CONSTRAINT notificacion_proyecto_seccion_fkey
      FOREIGN KEY (id_seccion_proyecto)
      REFERENCES public.catalogo_seccion_proyecto_notificacion(id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_proyecto_usuario_actor_fkey' AND conrelid = 'public.notificacion_proyecto'::regclass) THEN
    ALTER TABLE public.notificacion_proyecto
      ADD CONSTRAINT notificacion_proyecto_usuario_actor_fkey
      FOREIGN KEY (id_usuario_actor)
      REFERENCES public.usuario(id)
      ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_backlog_item_sugerencia_tipo_fkey' AND conrelid = 'public.notificacion_backlog_item_sugerencia'::regclass) THEN
    ALTER TABLE public.notificacion_backlog_item_sugerencia
      ADD CONSTRAINT notificacion_backlog_item_sugerencia_tipo_fkey
      FOREIGN KEY (id_notificacion, id_tipo_notificacion)
      REFERENCES public.notificacion(id, id_tipo_notificacion)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_backlog_item_sugerencia_backlog_fkey' AND conrelid = 'public.notificacion_backlog_item_sugerencia'::regclass) THEN
    ALTER TABLE public.notificacion_backlog_item_sugerencia
      ADD CONSTRAINT notificacion_backlog_item_sugerencia_backlog_fkey
      FOREIGN KEY (id_backlog_item)
      REFERENCES public.backlog_item_sugerencia_creacion(id)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_backlog_item_vencimiento_tipo_fkey' AND conrelid = 'public.notificacion_backlog_item_vencimiento'::regclass) THEN
    ALTER TABLE public.notificacion_backlog_item_vencimiento
      ADD CONSTRAINT notificacion_backlog_item_vencimiento_tipo_fkey
      FOREIGN KEY (id_notificacion, id_tipo_notificacion)
      REFERENCES public.notificacion(id, id_tipo_notificacion)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_backlog_item_vencimiento_backlog_fkey' AND conrelid = 'public.notificacion_backlog_item_vencimiento'::regclass) THEN
    ALTER TABLE public.notificacion_backlog_item_vencimiento
      ADD CONSTRAINT notificacion_backlog_item_vencimiento_backlog_fkey
      FOREIGN KEY (id_backlog_item, id_proyecto)
      REFERENCES public.backlog_item(id, id_proyecto)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_backlog_item_cambio_tipo_fkey' AND conrelid = 'public.notificacion_backlog_item_cambio'::regclass) THEN
    ALTER TABLE public.notificacion_backlog_item_cambio
      ADD CONSTRAINT notificacion_backlog_item_cambio_tipo_fkey
      FOREIGN KEY (id_notificacion, id_tipo_notificacion)
      REFERENCES public.notificacion(id, id_tipo_notificacion)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_backlog_item_cambio_backlog_fkey' AND conrelid = 'public.notificacion_backlog_item_cambio'::regclass) THEN
    ALTER TABLE public.notificacion_backlog_item_cambio
      ADD CONSTRAINT notificacion_backlog_item_cambio_backlog_fkey
      FOREIGN KEY (id_backlog_item, id_proyecto)
      REFERENCES public.backlog_item(id, id_proyecto)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_backlog_item_creacion_tipo_fkey' AND conrelid = 'public.notificacion_backlog_item_creacion'::regclass) THEN
    ALTER TABLE public.notificacion_backlog_item_creacion
      ADD CONSTRAINT notificacion_backlog_item_creacion_tipo_fkey
      FOREIGN KEY (id_notificacion, id_tipo_notificacion)
      REFERENCES public.notificacion(id, id_tipo_notificacion)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_backlog_item_creacion_backlog_fkey' AND conrelid = 'public.notificacion_backlog_item_creacion'::regclass) THEN
    ALTER TABLE public.notificacion_backlog_item_creacion
      ADD CONSTRAINT notificacion_backlog_item_creacion_backlog_fkey
      FOREIGN KEY (id_backlog_item, id_proyecto)
      REFERENCES public.backlog_item(id, id_proyecto)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_sprint_vencimiento_tipo_fkey' AND conrelid = 'public.notificacion_sprint_vencimiento'::regclass) THEN
    ALTER TABLE public.notificacion_sprint_vencimiento
      ADD CONSTRAINT notificacion_sprint_vencimiento_tipo_fkey
      FOREIGN KEY (id_notificacion, id_tipo_notificacion)
      REFERENCES public.notificacion(id, id_tipo_notificacion)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_sprint_vencimiento_sprint_fkey' AND conrelid = 'public.notificacion_sprint_vencimiento'::regclass) THEN
    ALTER TABLE public.notificacion_sprint_vencimiento
      ADD CONSTRAINT notificacion_sprint_vencimiento_sprint_fkey
      FOREIGN KEY (id_sprint, id_proyecto)
      REFERENCES public.sprint(id, id_proyecto)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_backlog_item_vencimiento_registro_usuario_fkey' AND conrelid = 'public.notificacion_backlog_item_vencimiento_registro'::regclass) THEN
    ALTER TABLE public.notificacion_backlog_item_vencimiento_registro
      ADD CONSTRAINT notificacion_backlog_item_vencimiento_registro_usuario_fkey
      FOREIGN KEY (id_usuario)
      REFERENCES public.usuario(id)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_backlog_item_vencimiento_registro_backlog_fkey' AND conrelid = 'public.notificacion_backlog_item_vencimiento_registro'::regclass) THEN
    ALTER TABLE public.notificacion_backlog_item_vencimiento_registro
      ADD CONSTRAINT notificacion_backlog_item_vencimiento_registro_backlog_fkey
      FOREIGN KEY (id_backlog_item)
      REFERENCES public.backlog_item(id)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_backlog_item_vencimiento_registro_notificacion_fkey' AND conrelid = 'public.notificacion_backlog_item_vencimiento_registro'::regclass) THEN
    ALTER TABLE public.notificacion_backlog_item_vencimiento_registro
      ADD CONSTRAINT notificacion_backlog_item_vencimiento_registro_notificacion_fkey
      FOREIGN KEY (id_notificacion)
      REFERENCES public.notificacion(id)
      ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_sprint_vencimiento_registro_usuario_fkey' AND conrelid = 'public.notificacion_sprint_vencimiento_registro'::regclass) THEN
    ALTER TABLE public.notificacion_sprint_vencimiento_registro
      ADD CONSTRAINT notificacion_sprint_vencimiento_registro_usuario_fkey
      FOREIGN KEY (id_usuario)
      REFERENCES public.usuario(id)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_sprint_vencimiento_registro_sprint_fkey' AND conrelid = 'public.notificacion_sprint_vencimiento_registro'::regclass) THEN
    ALTER TABLE public.notificacion_sprint_vencimiento_registro
      ADD CONSTRAINT notificacion_sprint_vencimiento_registro_sprint_fkey
      FOREIGN KEY (id_sprint)
      REFERENCES public.sprint(id)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notificacion_sprint_vencimiento_registro_notificacion_fkey' AND conrelid = 'public.notificacion_sprint_vencimiento_registro'::regclass) THEN
    ALTER TABLE public.notificacion_sprint_vencimiento_registro
      ADD CONSTRAINT notificacion_sprint_vencimiento_registro_notificacion_fkey
      FOREIGN KEY (id_notificacion)
      REFERENCES public.notificacion(id)
      ON DELETE SET NULL;
  END IF;
END $$;

-- Índices para lectura de feed y resolución de detalles
CREATE INDEX IF NOT EXISTS idx_notificacion_usuario_fecha ON public.notificacion (id_usuario, fecha_envio DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_notificacion_usuario_leida_fecha ON public.notificacion (id_usuario, leida, fecha_envio DESC);
CREATE INDEX IF NOT EXISTS idx_notificacion_tipo ON public.notificacion (id_tipo_notificacion);
CREATE UNIQUE INDEX IF NOT EXISTS idx_notificacion_invitacion_proyecto_unique_invitacion ON public.notificacion_invitacion_proyecto (id_invitacion_proyecto);
CREATE INDEX IF NOT EXISTS idx_notificacion_proyecto_proyecto ON public.notificacion_proyecto (id_proyecto);
CREATE INDEX IF NOT EXISTS idx_notificacion_backlog_item_sugerencia_backlog ON public.notificacion_backlog_item_sugerencia (id_backlog_item);
CREATE INDEX IF NOT EXISTS idx_notificacion_backlog_item_vencimiento_backlog ON public.notificacion_backlog_item_vencimiento (id_backlog_item);
CREATE INDEX IF NOT EXISTS idx_notificacion_backlog_item_vencimiento_proyecto ON public.notificacion_backlog_item_vencimiento (id_proyecto);
CREATE INDEX IF NOT EXISTS idx_notificacion_backlog_item_cambio_backlog ON public.notificacion_backlog_item_cambio (id_backlog_item);
CREATE INDEX IF NOT EXISTS idx_notificacion_backlog_item_cambio_proyecto ON public.notificacion_backlog_item_cambio (id_proyecto);
CREATE INDEX IF NOT EXISTS idx_notificacion_backlog_item_creacion_backlog ON public.notificacion_backlog_item_creacion (id_backlog_item);
CREATE INDEX IF NOT EXISTS idx_notificacion_backlog_item_creacion_proyecto ON public.notificacion_backlog_item_creacion (id_proyecto);
CREATE INDEX IF NOT EXISTS idx_notificacion_sprint_vencimiento_sprint ON public.notificacion_sprint_vencimiento (id_sprint);
CREATE INDEX IF NOT EXISTS idx_notificacion_sprint_vencimiento_proyecto ON public.notificacion_sprint_vencimiento (id_proyecto);
CREATE INDEX IF NOT EXISTS idx_suscripcion_notificacion_backlog_item_backlog ON public.suscripcion_notificacion_backlog_item (id_backlog_item);
CREATE INDEX IF NOT EXISTS idx_suscripcion_notificacion_backlog_item_usuario ON public.suscripcion_notificacion_backlog_item (id_usuario);

-- Funciones auxiliares seguras
CREATE OR REPLACE FUNCTION public.obtener_id_tipo_notificacion(p_codigo text)
RETURNS smallint
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_id smallint;
BEGIN
  SELECT c.id
  INTO v_id
  FROM public.catalogo_tipo_notificacion c
  WHERE c.codigo = p_codigo
    AND c.activo = true;

  IF v_id IS NULL THEN
    RAISE EXCEPTION 'Tipo de notificación no configurado: %', p_codigo
      USING ERRCODE = '23503';
  END IF;

  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.obtener_id_seccion_proyecto_notificacion(p_codigo text)
RETURNS smallint
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_id smallint;
BEGIN
  SELECT s.id
  INTO v_id
  FROM public.catalogo_seccion_proyecto_notificacion s
  WHERE s.codigo = p_codigo
    AND s.activo = true;

  IF v_id IS NULL THEN
    RAISE EXCEPTION 'Sección de notificación no configurada: %', p_codigo
      USING ERRCODE = '23503';
  END IF;

  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.obtener_id_usuario_actual()
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
  SELECT u.id
  FROM public.usuario u
  WHERE auth.uid() IS NOT NULL
    AND u.auth_id = auth.uid()
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.crear_notificacion_base(
  p_id_usuario integer,
  p_codigo_tipo text,
  p_nombre text,
  p_descripcion text
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_id_tipo smallint;
  v_id_notificacion integer;
BEGIN
  IF p_id_usuario IS NULL THEN
    RAISE EXCEPTION 'El usuario destino de la notificación es obligatorio.'
      USING ERRCODE = '23502';
  END IF;

  SELECT public.obtener_id_tipo_notificacion(p_codigo_tipo)
  INTO v_id_tipo;

  INSERT INTO public.notificacion (
    nombre,
    descripcion,
    id_usuario,
    id_tipo_notificacion
  )
  VALUES (
    LEFT(COALESCE(NULLIF(BTRIM(p_nombre), ''), 'Notificación'), 50),
    LEFT(p_descripcion, 100),
    p_id_usuario,
    v_id_tipo
  )
  RETURNING id INTO v_id_notificacion;

  RETURN v_id_notificacion;
END;
$$;

-- Creación manual o interna de notificaciones por tipo
CREATE OR REPLACE FUNCTION public.crear_notificaciones_proyecto(
  p_id_proyecto integer,
  p_codigo_seccion character varying DEFAULT 'general',
  p_nombre character varying DEFAULT 'Proyecto actualizado',
  p_descripcion character varying DEFAULT NULL,
  p_id_usuario_actor integer DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_proyecto public.proyecto%ROWTYPE;
  v_id_seccion smallint;
  v_id_notificacion integer;
  v_total integer := 0;
  v_recipient record;
BEGIN
  SELECT * INTO v_proyecto
  FROM public.proyecto
  WHERE id = p_id_proyecto;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Proyecto no encontrado: %', p_id_proyecto
      USING ERRCODE = 'P0002';
  END IF;

  SELECT public.obtener_id_seccion_proyecto_notificacion(COALESCE(NULLIF(p_codigo_seccion, ''), 'general'))
  INTO v_id_seccion;

  FOR v_recipient IN
    SELECT DISTINCT u.id AS id_usuario
    FROM public.usuario u
    JOIN public.usuario_proyecto up ON up.id_usuario = u.id
    WHERE up.id_proyecto = p_id_proyecto
      AND u.activo = true
      AND (p_id_usuario_actor IS NULL OR u.id IS DISTINCT FROM p_id_usuario_actor)
  LOOP
    v_id_notificacion := public.crear_notificacion_base(
      v_recipient.id_usuario,
      'cambio_proyecto',
      COALESCE(NULLIF(p_nombre, ''), 'Proyecto actualizado'),
      COALESCE(p_descripcion, 'Se actualizó el proyecto "' || v_proyecto.nombre || '".')
    );

    INSERT INTO public.notificacion_proyecto (
      id_notificacion,
      id_proyecto,
      id_seccion_proyecto,
      id_usuario_actor
    )
    VALUES (
      v_id_notificacion,
      p_id_proyecto,
      v_id_seccion,
      p_id_usuario_actor
    );

    v_total := v_total + 1;
  END LOOP;

  RETURN v_total;
END;
$$;

CREATE OR REPLACE FUNCTION public.crear_notificaciones_cambio_backlog_item(
  p_id_backlog_item bigint,
  p_id_usuario_actor integer DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_item record;
  v_id_notificacion integer;
  v_total integer := 0;
  v_recipient record;
BEGIN
  SELECT bi.id,
         bi.nombre,
         bi.id_proyecto,
         bi.id_usuario_responsable,
         p.nombre AS nombre_proyecto
  INTO v_item
  FROM public.backlog_item bi
  JOIN public.proyecto p ON p.id = bi.id_proyecto
  WHERE bi.id = p_id_backlog_item;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Backlog item no encontrado: %', p_id_backlog_item
      USING ERRCODE = 'P0002';
  END IF;

  FOR v_recipient IN
    SELECT DISTINCT x.id_usuario
    FROM (
      SELECT v_item.id_usuario_responsable AS id_usuario
      WHERE v_item.id_usuario_responsable IS NOT NULL
      UNION
      SELECT s.id_usuario
      FROM public.suscripcion_notificacion_backlog_item s
      WHERE s.id_backlog_item = v_item.id
    ) x
    JOIN public.usuario u ON u.id = x.id_usuario
    WHERE x.id_usuario IS NOT NULL
      AND u.activo = true
      AND (p_id_usuario_actor IS NULL OR x.id_usuario IS DISTINCT FROM p_id_usuario_actor)
  LOOP
    v_id_notificacion := public.crear_notificacion_base(
      v_recipient.id_usuario,
      'cambio_backlog_item',
      'Backlog item actualizado',
      'Se actualizó "' || v_item.nombre || '" en el proyecto "' || v_item.nombre_proyecto || '".'
    );

    INSERT INTO public.notificacion_backlog_item_cambio (
      id_notificacion,
      id_backlog_item,
      id_proyecto
    )
    VALUES (
      v_id_notificacion,
      v_item.id,
      v_item.id_proyecto
    );

    v_total := v_total + 1;
  END LOOP;

  RETURN v_total;
END;
$$;

CREATE OR REPLACE FUNCTION public.crear_notificacion_creacion_backlog_item(
  p_id_backlog_item bigint
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_item record;
  v_id_notificacion integer;
BEGIN
  SELECT bi.id,
         bi.nombre,
         bi.id_proyecto,
         bi.id_usuario_responsable,
         p.nombre AS nombre_proyecto
  INTO v_item
  FROM public.backlog_item bi
  JOIN public.proyecto p ON p.id = bi.id_proyecto
  WHERE bi.id = p_id_backlog_item;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Backlog item no encontrado: %', p_id_backlog_item
      USING ERRCODE = 'P0002';
  END IF;

  IF v_item.id_usuario_responsable IS NULL THEN
    RETURN NULL;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.backlog_item_sugerencia_creacion s
    WHERE s.id = v_item.id
  ) THEN
    RETURN NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.usuario u
    WHERE u.id = v_item.id_usuario_responsable
      AND u.activo = true
  ) THEN
    RETURN NULL;
  END IF;

  v_id_notificacion := public.crear_notificacion_base(
    v_item.id_usuario_responsable,
    'creacion_backlog_item',
    'Backlog item asignado',
    'Se te asignó "' || v_item.nombre || '" en el proyecto "' || v_item.nombre_proyecto || '".'
  );

  INSERT INTO public.notificacion_backlog_item_creacion (
    id_notificacion,
    id_backlog_item,
    id_proyecto
  )
  VALUES (
    v_id_notificacion,
    v_item.id,
    v_item.id_proyecto
  );

  RETURN v_id_notificacion;
END;
$$;

CREATE OR REPLACE FUNCTION public.crear_notificaciones_sugerencia_backlog_item(
  p_id_backlog_item bigint,
  p_id_usuario_actor integer DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_item record;
  v_id_notificacion integer;
  v_total integer := 0;
  v_recipient record;
BEGIN
  SELECT bi.id,
         bi.nombre,
         bi.id_proyecto,
         p.nombre AS nombre_proyecto
  INTO v_item
  FROM public.backlog_item bi
  JOIN public.backlog_item_sugerencia_creacion s ON s.id = bi.id
  JOIN public.proyecto p ON p.id = bi.id_proyecto
  WHERE bi.id = p_id_backlog_item;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Sugerencia de backlog item no encontrada: %', p_id_backlog_item
      USING ERRCODE = 'P0002';
  END IF;

  FOR v_recipient IN
    SELECT DISTINCT epp.id_usuario
    FROM public.etiqueta_proyecto_predeterminada epp
    JOIN public.catalogo_etiqueta_proyecto_predeterminada cepp
      ON cepp.id = epp.id_etiqueta_proyecto_predeterminada
    JOIN public.usuario u ON u.id = epp.id_usuario
    WHERE epp.id_proyecto = v_item.id_proyecto
      AND UPPER(cepp.nombre::text) = 'PM'
      AND u.activo = true
      AND (p_id_usuario_actor IS NULL OR epp.id_usuario IS DISTINCT FROM p_id_usuario_actor)
  LOOP
    IF NOT EXISTS (
      SELECT 1
      FROM public.notificacion n
      JOIN public.notificacion_backlog_item_sugerencia d
        ON d.id_notificacion = n.id
      WHERE n.id_usuario = v_recipient.id_usuario
        AND d.id_backlog_item = v_item.id
    ) THEN
      v_id_notificacion := public.crear_notificacion_base(
        v_recipient.id_usuario,
        'sugerencia_creacion_backlog_item',
        'Nueva sugerencia de backlog item',
        'Se sugirió "' || v_item.nombre || '" para el proyecto "' || v_item.nombre_proyecto || '".'
      );

      INSERT INTO public.notificacion_backlog_item_sugerencia (
        id_notificacion,
        id_backlog_item
      )
      VALUES (
        v_id_notificacion,
        v_item.id
      );

      v_total := v_total + 1;
    END IF;
  END LOOP;

  RETURN v_total;
END;
$$;

CREATE OR REPLACE FUNCTION public.crear_notificacion_invitacion_proyecto(p_invitacion_id integer)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_inv record;
  v_id_notificacion integer;
BEGIN
  SELECT ip.id,
         ip.id_usuario_destino,
         ip.id_proyecto,
         ip.aceptada,
         p.nombre AS nombre_proyecto
  INTO v_inv
  FROM public.invitacion_proyecto ip
  JOIN public.proyecto p ON p.id = ip.id_proyecto
  WHERE ip.id = p_invitacion_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invitación no encontrada: %', p_invitacion_id
      USING ERRCODE = 'P0002';
  END IF;

  IF v_inv.aceptada = true THEN
    RETURN NULL;
  END IF;

  SELECT d.id_notificacion
  INTO v_id_notificacion
  FROM public.notificacion_invitacion_proyecto d
  WHERE d.id_invitacion_proyecto = p_invitacion_id;

  IF v_id_notificacion IS NOT NULL THEN
    RETURN v_id_notificacion;
  END IF;

  v_id_notificacion := public.crear_notificacion_base(
    v_inv.id_usuario_destino,
    'invitacion_proyecto',
    'Invitación a proyecto',
    'Fuiste invitado al proyecto "' || v_inv.nombre_proyecto || '".'
  );

  INSERT INTO public.notificacion_invitacion_proyecto (
    id_notificacion,
    id_invitacion_proyecto
  )
  VALUES (
    v_id_notificacion,
    p_invitacion_id
  );

  RETURN v_id_notificacion;
END;
$$;

-- Funciones programables para vencimientos
CREATE OR REPLACE FUNCTION public.generar_notificaciones_backlog_items_proximos_vencer(p_horas_anticipacion integer DEFAULT 24)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_total integer := 0;
  v_id_notificacion integer;
  v_item record;
  v_recipient record;
BEGIN
  IF p_horas_anticipacion IS NULL OR p_horas_anticipacion <= 0 THEN
    RAISE EXCEPTION 'p_horas_anticipacion debe ser mayor a 0.'
      USING ERRCODE = '22023';
  END IF;

  FOR v_item IN
    SELECT bi.id,
           bi.nombre,
           bi.fecha_vencimiento,
           bi.id_proyecto,
           bi.id_usuario_responsable,
           p.nombre AS nombre_proyecto
    FROM public.backlog_item bi
    JOIN public.proyecto p ON p.id = bi.id_proyecto
    WHERE bi.fecha_vencimiento IS NOT NULL
      AND bi.fecha_vencimiento > now()
      AND bi.fecha_vencimiento <= now() + make_interval(hours => p_horas_anticipacion)
      AND bi.es_terminal = false
  LOOP
    FOR v_recipient IN
      SELECT DISTINCT x.id_usuario
      FROM (
        SELECT v_item.id_usuario_responsable AS id_usuario
        WHERE v_item.id_usuario_responsable IS NOT NULL
        UNION
        SELECT s.id_usuario
        FROM public.suscripcion_notificacion_backlog_item s
        WHERE s.id_backlog_item = v_item.id
      ) x
      JOIN public.usuario u ON u.id = x.id_usuario
      WHERE x.id_usuario IS NOT NULL
        AND u.activo = true
    LOOP
      INSERT INTO public.notificacion_backlog_item_vencimiento_registro (
        id_usuario,
        id_backlog_item,
        fecha_vencimiento_notificada
      )
      VALUES (
        v_recipient.id_usuario,
        v_item.id,
        v_item.fecha_vencimiento
      )
      ON CONFLICT DO NOTHING;

      IF FOUND THEN
        v_id_notificacion := public.crear_notificacion_base(
          v_recipient.id_usuario,
          'backlog_item_proximo_vencer',
          'Backlog item por vencer',
          '"' || v_item.nombre || '" del proyecto "' || v_item.nombre_proyecto || '" vence el ' || to_char(v_item.fecha_vencimiento, 'YYYY-MM-DD HH24:MI') || '.'
        );

        INSERT INTO public.notificacion_backlog_item_vencimiento (
          id_notificacion,
          id_backlog_item,
          id_proyecto,
          fecha_vencimiento_notificada
        )
        VALUES (
          v_id_notificacion,
          v_item.id,
          v_item.id_proyecto,
          v_item.fecha_vencimiento
        );

        UPDATE public.notificacion_backlog_item_vencimiento_registro r
        SET id_notificacion = v_id_notificacion
        WHERE r.id_usuario = v_recipient.id_usuario
          AND r.id_backlog_item = v_item.id
          AND r.fecha_vencimiento_notificada = v_item.fecha_vencimiento;

        v_total := v_total + 1;
      END IF;
    END LOOP;
  END LOOP;

  RETURN v_total;
END;
$$;

CREATE OR REPLACE FUNCTION public.generar_notificaciones_sprints_proximos_vencer(p_horas_anticipacion integer DEFAULT 24)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_total integer := 0;
  v_id_notificacion integer;
  v_sprint record;
  v_recipient record;
BEGIN
  IF p_horas_anticipacion IS NULL OR p_horas_anticipacion <= 0 THEN
    RAISE EXCEPTION 'p_horas_anticipacion debe ser mayor a 0.'
      USING ERRCODE = '22023';
  END IF;

  FOR v_sprint IN
    SELECT s.id,
           s.nombre,
           s.fecha_final,
           s.id_proyecto,
           p.nombre AS nombre_proyecto
    FROM public.sprint s
    JOIN public.proyecto p ON p.id = s.id_proyecto
    JOIN public.estatus_sprint es ON es.id = s.id_estatus
    WHERE s.fecha_final IS NOT NULL
      AND s.fecha_final > now()
      AND s.fecha_final <= now() + make_interval(hours => p_horas_anticipacion)
      AND es.es_terminal = false
  LOOP
    FOR v_recipient IN
      SELECT DISTINCT epp.id_usuario
      FROM public.etiqueta_proyecto_predeterminada epp
      JOIN public.catalogo_etiqueta_proyecto_predeterminada cepp
        ON cepp.id = epp.id_etiqueta_proyecto_predeterminada
      JOIN public.usuario u ON u.id = epp.id_usuario
      WHERE epp.id_proyecto = v_sprint.id_proyecto
        AND UPPER(cepp.nombre::text) = 'PM'
        AND u.activo = true
    LOOP
      INSERT INTO public.notificacion_sprint_vencimiento_registro (
        id_usuario,
        id_sprint,
        fecha_final_notificada
      )
      VALUES (
        v_recipient.id_usuario,
        v_sprint.id,
        v_sprint.fecha_final
      )
      ON CONFLICT DO NOTHING;

      IF FOUND THEN
        v_id_notificacion := public.crear_notificacion_base(
          v_recipient.id_usuario,
          'sprint_proximo_vencer',
          'Sprint por finalizar',
          '"' || v_sprint.nombre || '" del proyecto "' || v_sprint.nombre_proyecto || '" finaliza el ' || to_char(v_sprint.fecha_final, 'YYYY-MM-DD HH24:MI') || '.'
        );

        INSERT INTO public.notificacion_sprint_vencimiento (
          id_notificacion,
          id_sprint,
          id_proyecto,
          fecha_final_notificada
        )
        VALUES (
          v_id_notificacion,
          v_sprint.id,
          v_sprint.id_proyecto,
          v_sprint.fecha_final
        );

        UPDATE public.notificacion_sprint_vencimiento_registro r
        SET id_notificacion = v_id_notificacion
        WHERE r.id_usuario = v_recipient.id_usuario
          AND r.id_sprint = v_sprint.id
          AND r.fecha_final_notificada = v_sprint.fecha_final;

        v_total := v_total + 1;
      END IF;
    END LOOP;
  END LOOP;

  RETURN v_total;
END;
$$;

-- Triggers de generación automática
CREATE OR REPLACE FUNCTION public.trg_generar_notificaciones_cambio_proyecto()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_actor integer;
BEGIN
  IF ROW(OLD.nombre, OLD.descripcion, OLD.fecha_inicial, OLD.fecha_final, OLD.id_estatus, OLD.stack_tecnologico)
     IS NOT DISTINCT FROM
     ROW(NEW.nombre, NEW.descripcion, NEW.fecha_inicial, NEW.fecha_final, NEW.id_estatus, NEW.stack_tecnologico) THEN
    RETURN NEW;
  END IF;

  SELECT public.obtener_id_usuario_actual()
  INTO v_actor;

  PERFORM public.crear_notificaciones_proyecto(
    NEW.id,
    'general',
    'Proyecto actualizado',
    'Se actualizó el proyecto "' || NEW.nombre || '".',
    v_actor
  );

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_generar_notificaciones_cambio_backlog_item()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_actor integer;
BEGIN
  IF ROW(OLD.nombre, OLD.descripcion, OLD.fecha_inicio, OLD.fecha_vencimiento, OLD.es_terminal, OLD.id_usuario_responsable, OLD.id_prioridad, OLD.id_tipo, OLD.id_estatus, OLD.id_sprint, OLD.complejidad, OLD.tiempo)
     IS NOT DISTINCT FROM
     ROW(NEW.nombre, NEW.descripcion, NEW.fecha_inicio, NEW.fecha_vencimiento, NEW.es_terminal, NEW.id_usuario_responsable, NEW.id_prioridad, NEW.id_tipo, NEW.id_estatus, NEW.id_sprint, NEW.complejidad, NEW.tiempo) THEN
    RETURN NEW;
  END IF;

  SELECT public.obtener_id_usuario_actual()
  INTO v_actor;

  PERFORM public.crear_notificaciones_cambio_backlog_item(NEW.id, v_actor);

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_generar_notificacion_creacion_backlog_item()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  PERFORM public.crear_notificacion_creacion_backlog_item(NEW.id);
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_generar_notificaciones_sugerencia_creacion_backlog_item()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_actor integer;
BEGIN
  SELECT bi.id_usuario_creador
  INTO v_actor
  FROM public.backlog_item bi
  WHERE bi.id = NEW.id;

  PERFORM public.crear_notificaciones_sugerencia_backlog_item(NEW.id, v_actor);
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_generar_notificacion_invitacion_proyecto()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  PERFORM public.crear_notificacion_invitacion_proyecto(NEW.id);
  RETURN NEW;
END;
$$;

-- Triggers de limpieza para cambios de estado o borrado de referencias
CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_de_invitacion()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  DELETE FROM public.notificacion n
  USING public.notificacion_invitacion_proyecto d
  WHERE d.id_notificacion = n.id
    AND d.id_invitacion_proyecto = OLD.id;

  RETURN OLD;
END;
$$;

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_de_invitacion_aceptada()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  IF NEW.aceptada = true AND OLD.aceptada IS DISTINCT FROM true THEN
    DELETE FROM public.notificacion n
    USING public.notificacion_invitacion_proyecto d
    WHERE d.id_notificacion = n.id
      AND d.id_invitacion_proyecto = NEW.id;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_de_sugerencia_aceptada()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  IF NEW.aceptada = true AND OLD.aceptada IS DISTINCT FROM true THEN
    DELETE FROM public.notificacion n
    USING public.notificacion_backlog_item_sugerencia d
    WHERE d.id_notificacion = n.id
      AND d.id_backlog_item = NEW.id;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_de_sugerencia_borrada()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  DELETE FROM public.notificacion n
  USING public.notificacion_backlog_item_sugerencia d
  WHERE d.id_notificacion = n.id
    AND d.id_backlog_item = OLD.id;

  RETURN OLD;
END;
$$;

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_de_proyecto()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  DELETE FROM public.notificacion n
  USING public.notificacion_proyecto d
  WHERE d.id_notificacion = n.id
    AND d.id_proyecto = OLD.id;

  DELETE FROM public.notificacion n
  USING public.notificacion_backlog_item_cambio d
  WHERE d.id_notificacion = n.id
    AND d.id_proyecto = OLD.id;

  DELETE FROM public.notificacion n
  USING public.notificacion_backlog_item_creacion d
  WHERE d.id_notificacion = n.id
    AND d.id_proyecto = OLD.id;

  DELETE FROM public.notificacion n
  USING public.notificacion_backlog_item_vencimiento d
  WHERE d.id_notificacion = n.id
    AND d.id_proyecto = OLD.id;

  DELETE FROM public.notificacion n
  USING public.notificacion_sprint_vencimiento d
  WHERE d.id_notificacion = n.id
    AND d.id_proyecto = OLD.id;

  RETURN OLD;
END;
$$;

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_de_backlog_item()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  DELETE FROM public.notificacion n
  USING public.notificacion_backlog_item_cambio d
  WHERE d.id_notificacion = n.id
    AND d.id_backlog_item = OLD.id;

  DELETE FROM public.notificacion n
  USING public.notificacion_backlog_item_creacion d
  WHERE d.id_notificacion = n.id
    AND d.id_backlog_item = OLD.id;

  DELETE FROM public.notificacion n
  USING public.notificacion_backlog_item_vencimiento d
  WHERE d.id_notificacion = n.id
    AND d.id_backlog_item = OLD.id;

  RETURN OLD;
END;
$$;

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_vencimiento_backlog_item_resuelto()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  IF NEW.es_terminal = true OR NEW.fecha_vencimiento IS DISTINCT FROM OLD.fecha_vencimiento THEN
    DELETE FROM public.notificacion n
    USING public.notificacion_backlog_item_vencimiento d
    WHERE d.id_notificacion = n.id
      AND d.id_backlog_item = NEW.id;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_vencimiento_sprint_borrado()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
BEGIN
  DELETE FROM public.notificacion n
  USING public.notificacion_sprint_vencimiento d
  WHERE d.id_notificacion = n.id
    AND d.id_sprint = OLD.id;

  DELETE FROM public.notificacion n
  WHERE n.id IN (
    SELECT r.id_notificacion
    FROM public.notificacion_sprint_vencimiento_registro r
    WHERE r.id_sprint = OLD.id
      AND r.id_notificacion IS NOT NULL
  );

  RETURN OLD;
END;
$$;

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_vencimiento_sprint_resuelto()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_es_terminal boolean;
BEGIN
  SELECT es.es_terminal
  INTO v_es_terminal
  FROM public.estatus_sprint es
  WHERE es.id = NEW.id_estatus;

  IF COALESCE(v_es_terminal, false) = true OR NEW.fecha_final IS DISTINCT FROM OLD.fecha_final THEN
    DELETE FROM public.notificacion n
    USING public.notificacion_sprint_vencimiento d
    WHERE d.id_notificacion = n.id
      AND d.id_sprint = NEW.id;

    DELETE FROM public.notificacion n
    WHERE n.id IN (
      SELECT r.id_notificacion
      FROM public.notificacion_sprint_vencimiento_registro r
      WHERE r.id_sprint = NEW.id
        AND r.id_notificacion IS NOT NULL
    );
  END IF;

  RETURN NEW;
END;
$$;

-- Funciones para el frontend: marcar leída/no leída sin permisos privilegiados
CREATE OR REPLACE FUNCTION public.marcar_notificacion_como_leida(p_id_notificacion integer)
RETURNS public.notificacion
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_notificacion public.notificacion;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado.'
      USING ERRCODE = '28000';
  END IF;

  UPDATE public.notificacion n
  SET leida = true,
      fecha_lectura = COALESCE(n.fecha_lectura, now())
  WHERE n.id = p_id_notificacion
    AND EXISTS (
      SELECT 1
      FROM public.usuario u
      WHERE u.id = n.id_usuario
        AND u.auth_id = auth.uid()
    )
  RETURNING n.* INTO v_notificacion;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Notificación no encontrada o no permitida.'
      USING ERRCODE = '42501';
  END IF;

  RETURN v_notificacion;
END;
$$;

CREATE OR REPLACE FUNCTION public.marcar_notificacion_como_no_leida(p_id_notificacion integer)
RETURNS public.notificacion
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_notificacion public.notificacion;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado.'
      USING ERRCODE = '28000';
  END IF;

  UPDATE public.notificacion n
  SET leida = false,
      fecha_lectura = NULL
  WHERE n.id = p_id_notificacion
    AND EXISTS (
      SELECT 1
      FROM public.usuario u
      WHERE u.id = n.id_usuario
        AND u.auth_id = auth.uid()
    )
  RETURNING n.* INTO v_notificacion;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Notificación no encontrada o no permitida.'
      USING ERRCODE = '42501';
  END IF;

  RETURN v_notificacion;
END;
$$;

-- Compatibilidad con nombres previos si ya los usa el frontend
CREATE OR REPLACE FUNCTION public.mark_notification_as_read(notification_id integer)
RETURNS public.notificacion
LANGUAGE sql
SECURITY DEFINER
SET search_path TO ''
AS $$
  SELECT public.marcar_notificacion_como_leida(notification_id);
$$;

CREATE OR REPLACE FUNCTION public.mark_notification_as_unread(notification_id integer)
RETURNS public.notificacion
LANGUAGE sql
SECURITY DEFINER
SET search_path TO ''
AS $$
  SELECT public.marcar_notificacion_como_no_leida(notification_id);
$$;

-- Registro de triggers
DROP TRIGGER IF EXISTS trg_generar_notificaciones_cambio_proyecto ON public.proyecto;
CREATE TRIGGER trg_generar_notificaciones_cambio_proyecto
AFTER UPDATE OF nombre, descripcion, fecha_inicial, fecha_final, id_estatus, stack_tecnologico
ON public.proyecto
FOR EACH ROW
EXECUTE FUNCTION public.trg_generar_notificaciones_cambio_proyecto();

DROP TRIGGER IF EXISTS trg_generar_notificaciones_cambio_backlog_item ON public.backlog_item;
CREATE TRIGGER trg_generar_notificaciones_cambio_backlog_item
AFTER UPDATE OF nombre, descripcion, fecha_inicio, fecha_vencimiento, es_terminal, id_usuario_responsable, id_prioridad, id_tipo, id_estatus, id_sprint, complejidad, tiempo
ON public.backlog_item
FOR EACH ROW
EXECUTE FUNCTION public.trg_generar_notificaciones_cambio_backlog_item();

DROP TRIGGER IF EXISTS trg_generar_notificacion_creacion_backlog_item ON public.backlog_item;
CREATE CONSTRAINT TRIGGER trg_generar_notificacion_creacion_backlog_item
AFTER INSERT ON public.backlog_item
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.trg_generar_notificacion_creacion_backlog_item();

DROP TRIGGER IF EXISTS trg_generar_notificaciones_sugerencia_creacion_backlog_item ON public.backlog_item_sugerencia_creacion;
CREATE TRIGGER trg_generar_notificaciones_sugerencia_creacion_backlog_item
AFTER INSERT ON public.backlog_item_sugerencia_creacion
FOR EACH ROW
EXECUTE FUNCTION public.trg_generar_notificaciones_sugerencia_creacion_backlog_item();

DROP TRIGGER IF EXISTS trg_generar_notificacion_invitacion_proyecto ON public.invitacion_proyecto;
CREATE TRIGGER trg_generar_notificacion_invitacion_proyecto
AFTER INSERT ON public.invitacion_proyecto
FOR EACH ROW
EXECUTE FUNCTION public.trg_generar_notificacion_invitacion_proyecto();

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_de_invitacion ON public.invitacion_proyecto;
CREATE TRIGGER trg_eliminar_notificaciones_de_invitacion
BEFORE DELETE ON public.invitacion_proyecto
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_de_invitacion();

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_de_invitacion_aceptada ON public.invitacion_proyecto;
CREATE TRIGGER trg_eliminar_notificaciones_de_invitacion_aceptada
AFTER UPDATE OF aceptada ON public.invitacion_proyecto
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_de_invitacion_aceptada();

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_de_sugerencia_aceptada ON public.backlog_item_sugerencia_creacion;
CREATE TRIGGER trg_eliminar_notificaciones_de_sugerencia_aceptada
AFTER UPDATE OF aceptada ON public.backlog_item_sugerencia_creacion
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_de_sugerencia_aceptada();

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_de_sugerencia_borrada ON public.backlog_item_sugerencia_creacion;
CREATE TRIGGER trg_eliminar_notificaciones_de_sugerencia_borrada
BEFORE DELETE ON public.backlog_item_sugerencia_creacion
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_de_sugerencia_borrada();

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_de_proyecto ON public.proyecto;
CREATE TRIGGER trg_eliminar_notificaciones_de_proyecto
BEFORE DELETE ON public.proyecto
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_de_proyecto();

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_de_backlog_item ON public.backlog_item;
CREATE TRIGGER trg_eliminar_notificaciones_de_backlog_item
BEFORE DELETE ON public.backlog_item
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_de_backlog_item();

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_vencimiento_backlog_item ON public.backlog_item;
CREATE TRIGGER trg_eliminar_notificaciones_vencimiento_backlog_item
BEFORE DELETE ON public.backlog_item
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_de_backlog_item();

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_vencimiento_backlog_item_resuelto ON public.backlog_item;
CREATE TRIGGER trg_eliminar_notificaciones_vencimiento_backlog_item_resuelto
AFTER UPDATE OF es_terminal, fecha_vencimiento ON public.backlog_item
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_vencimiento_backlog_item_resuelto();

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_vencimiento_sprint_borrado ON public.sprint;
CREATE TRIGGER trg_eliminar_notificaciones_vencimiento_sprint_borrado
BEFORE DELETE ON public.sprint
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_vencimiento_sprint_borrado();

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_vencimiento_sprint_resuelto ON public.sprint;
CREATE TRIGGER trg_eliminar_notificaciones_vencimiento_sprint_resuelto
AFTER UPDATE OF id_estatus, fecha_final ON public.sprint
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_vencimiento_sprint_resuelto();

-- Vista final para el frontend
CREATE OR REPLACE VIEW public.notificacion_feed_view
WITH (security_invoker = true)
AS
SELECT
  n.id,
  n.nombre,
  n.descripcion,
  n.leida,
  n.fecha_lectura,
  n.id_usuario,
  n.fecha_envio,
  n.id_tipo_notificacion,
  c.codigo AS tipo_codigo,
  c.nombre AS tipo_nombre,
  nip.id_invitacion_proyecto,
  ip.aceptada AS invitacion_aceptada,
  np.id_proyecto AS id_proyecto_cambio,
  np.id_usuario_actor AS id_usuario_actor_proyecto,
  nbis.id_backlog_item AS id_backlog_item_sugerido,
  nbic.id_backlog_item AS id_backlog_item_cambio,
  nbicr.id_backlog_item AS id_backlog_item_creacion,
  nbiv.id_backlog_item AS id_backlog_item_por_vencer,
  nsv.id_sprint AS id_sprint_por_vencer,
  COALESCE(
    ip.id_proyecto,
    np.id_proyecto,
    bi_sug.id_proyecto,
    nbic.id_proyecto,
    nbicr.id_proyecto,
    nbiv.id_proyecto,
    nsv.id_proyecto
  ) AS id_proyecto_destino,
  COALESCE(
    p_inv.nombre,
    p_np.nombre,
    p_sug.nombre,
    p_cambio.nombre,
    p_creacion.nombre,
    p_vencimiento.nombre,
    p_sprint.nombre
  ) AS nombre_proyecto,
  COALESCE(
    nbis.id_backlog_item,
    nbic.id_backlog_item,
    nbicr.id_backlog_item,
    nbiv.id_backlog_item
  ) AS id_backlog_item,
  COALESCE(
    bi_sug.nombre,
    bi_cambio.nombre,
    bi_creacion.nombre,
    bi_vencimiento.nombre
  ) AS nombre_backlog_item,
  nsv.id_sprint AS id_sprint,
  spr.nombre AS nombre_sprint,
  nbiv.fecha_vencimiento_notificada,
  nsv.fecha_final_notificada,
  CASE
    WHEN c.codigo = 'invitacion_proyecto' THEN 'equipo'
    WHEN c.codigo IN ('sugerencia_creacion_backlog_item', 'cambio_backlog_item', 'creacion_backlog_item', 'backlog_item_proximo_vencer') THEN 'backlog'
    WHEN c.codigo = 'sprint_proximo_vencer' THEN 'sprints'
    WHEN c.codigo = 'cambio_proyecto' THEN COALESCE(csp.codigo, 'general')
    ELSE NULL
  END AS seccion_destino_codigo,
  CASE
    WHEN c.codigo = 'invitacion_proyecto' THEN 'equipo'
    WHEN c.codigo IN ('sugerencia_creacion_backlog_item', 'cambio_backlog_item', 'creacion_backlog_item', 'backlog_item_proximo_vencer') THEN 'backlog'
    WHEN c.codigo = 'sprint_proximo_vencer' THEN 'sprints'
    WHEN c.codigo = 'cambio_proyecto' THEN COALESCE(csp.ruta_relativa, 'general')
    ELSE NULL
  END AS seccion_destino_ruta
FROM public.notificacion n
JOIN public.catalogo_tipo_notificacion c
  ON c.id = n.id_tipo_notificacion
LEFT JOIN public.notificacion_invitacion_proyecto nip
  ON nip.id_notificacion = n.id
LEFT JOIN public.invitacion_proyecto ip
  ON ip.id = nip.id_invitacion_proyecto
LEFT JOIN public.proyecto p_inv
  ON p_inv.id = ip.id_proyecto
LEFT JOIN public.notificacion_proyecto np
  ON np.id_notificacion = n.id
LEFT JOIN public.proyecto p_np
  ON p_np.id = np.id_proyecto
LEFT JOIN public.catalogo_seccion_proyecto_notificacion csp
  ON csp.id = np.id_seccion_proyecto
LEFT JOIN public.notificacion_backlog_item_sugerencia nbis
  ON nbis.id_notificacion = n.id
LEFT JOIN public.backlog_item bi_sug
  ON bi_sug.id = nbis.id_backlog_item
LEFT JOIN public.proyecto p_sug
  ON p_sug.id = bi_sug.id_proyecto
LEFT JOIN public.notificacion_backlog_item_cambio nbic
  ON nbic.id_notificacion = n.id
LEFT JOIN public.backlog_item bi_cambio
  ON bi_cambio.id = nbic.id_backlog_item
LEFT JOIN public.proyecto p_cambio
  ON p_cambio.id = nbic.id_proyecto
LEFT JOIN public.notificacion_backlog_item_creacion nbicr
  ON nbicr.id_notificacion = n.id
LEFT JOIN public.backlog_item bi_creacion
  ON bi_creacion.id = nbicr.id_backlog_item
LEFT JOIN public.proyecto p_creacion
  ON p_creacion.id = nbicr.id_proyecto
LEFT JOIN public.notificacion_backlog_item_vencimiento nbiv
  ON nbiv.id_notificacion = n.id
LEFT JOIN public.backlog_item bi_vencimiento
  ON bi_vencimiento.id = nbiv.id_backlog_item
LEFT JOIN public.proyecto p_vencimiento
  ON p_vencimiento.id = nbiv.id_proyecto
LEFT JOIN public.notificacion_sprint_vencimiento nsv
  ON nsv.id_notificacion = n.id
LEFT JOIN public.sprint spr
  ON spr.id = nsv.id_sprint
LEFT JOIN public.proyecto p_sprint
  ON p_sprint.id = nsv.id_proyecto;

-- RLS para que cada usuario vea o borre solo sus notificaciones
ALTER TABLE public.notificacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_invitacion_proyecto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_proyecto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_backlog_item_sugerencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_backlog_item_vencimiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_backlog_item_cambio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_backlog_item_creacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_sprint_vencimiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_backlog_item_vencimiento_registro ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_sprint_vencimiento_registro ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalogo_tipo_notificacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalogo_seccion_proyecto_notificacion ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS catalogo_tipo_notificacion_select_authenticated ON public.catalogo_tipo_notificacion;
CREATE POLICY catalogo_tipo_notificacion_select_authenticated
ON public.catalogo_tipo_notificacion
FOR SELECT TO authenticated
USING (activo = true);

DROP POLICY IF EXISTS catalogo_seccion_proyecto_notificacion_select_authenticated ON public.catalogo_seccion_proyecto_notificacion;
CREATE POLICY catalogo_seccion_proyecto_notificacion_select_authenticated
ON public.catalogo_seccion_proyecto_notificacion
FOR SELECT TO authenticated
USING (activo = true);

DROP POLICY IF EXISTS notificacion_select_own ON public.notificacion;
CREATE POLICY notificacion_select_own
ON public.notificacion
FOR SELECT TO authenticated
USING (
  auth.uid() IS NOT NULL
  AND EXISTS (
    SELECT 1
    FROM public.usuario u
    WHERE u.id = public.notificacion.id_usuario
      AND u.auth_id = auth.uid()
  )
);

DROP POLICY IF EXISTS notificacion_update_own ON public.notificacion;
CREATE POLICY notificacion_update_own
ON public.notificacion
FOR UPDATE TO authenticated
USING (
  auth.uid() IS NOT NULL
  AND EXISTS (
    SELECT 1
    FROM public.usuario u
    WHERE u.id = public.notificacion.id_usuario
      AND u.auth_id = auth.uid()
  )
)
WITH CHECK (
  auth.uid() IS NOT NULL
  AND EXISTS (
    SELECT 1
    FROM public.usuario u
    WHERE u.id = public.notificacion.id_usuario
      AND u.auth_id = auth.uid()
  )
);

DROP POLICY IF EXISTS notificacion_delete_own ON public.notificacion;
CREATE POLICY notificacion_delete_own
ON public.notificacion
FOR DELETE TO authenticated
USING (
  auth.uid() IS NOT NULL
  AND EXISTS (
    SELECT 1
    FROM public.usuario u
    WHERE u.id = public.notificacion.id_usuario
      AND u.auth_id = auth.uid()
  )
);

DROP POLICY IF EXISTS notificacion_invitacion_proyecto_select_own ON public.notificacion_invitacion_proyecto;
CREATE POLICY notificacion_invitacion_proyecto_select_own
ON public.notificacion_invitacion_proyecto
FOR SELECT TO authenticated
USING (EXISTS (
  SELECT 1
  FROM public.notificacion n
  JOIN public.usuario u ON u.id = n.id_usuario
  WHERE n.id = public.notificacion_invitacion_proyecto.id_notificacion
    AND u.auth_id = auth.uid()
));

DROP POLICY IF EXISTS notificacion_proyecto_select_own ON public.notificacion_proyecto;
CREATE POLICY notificacion_proyecto_select_own
ON public.notificacion_proyecto
FOR SELECT TO authenticated
USING (EXISTS (
  SELECT 1
  FROM public.notificacion n
  JOIN public.usuario u ON u.id = n.id_usuario
  WHERE n.id = public.notificacion_proyecto.id_notificacion
    AND u.auth_id = auth.uid()
));

DROP POLICY IF EXISTS notificacion_backlog_item_sugerencia_select_own ON public.notificacion_backlog_item_sugerencia;
CREATE POLICY notificacion_backlog_item_sugerencia_select_own
ON public.notificacion_backlog_item_sugerencia
FOR SELECT TO authenticated
USING (EXISTS (
  SELECT 1
  FROM public.notificacion n
  JOIN public.usuario u ON u.id = n.id_usuario
  WHERE n.id = public.notificacion_backlog_item_sugerencia.id_notificacion
    AND u.auth_id = auth.uid()
));

DROP POLICY IF EXISTS notificacion_backlog_item_vencimiento_select_own ON public.notificacion_backlog_item_vencimiento;
CREATE POLICY notificacion_backlog_item_vencimiento_select_own
ON public.notificacion_backlog_item_vencimiento
FOR SELECT TO authenticated
USING (EXISTS (
  SELECT 1
  FROM public.notificacion n
  JOIN public.usuario u ON u.id = n.id_usuario
  WHERE n.id = public.notificacion_backlog_item_vencimiento.id_notificacion
    AND u.auth_id = auth.uid()
));

DROP POLICY IF EXISTS notificacion_backlog_item_cambio_select_own ON public.notificacion_backlog_item_cambio;
CREATE POLICY notificacion_backlog_item_cambio_select_own
ON public.notificacion_backlog_item_cambio
FOR SELECT TO authenticated
USING (EXISTS (
  SELECT 1
  FROM public.notificacion n
  JOIN public.usuario u ON u.id = n.id_usuario
  WHERE n.id = public.notificacion_backlog_item_cambio.id_notificacion
    AND u.auth_id = auth.uid()
));

DROP POLICY IF EXISTS notificacion_backlog_item_creacion_select_own ON public.notificacion_backlog_item_creacion;
CREATE POLICY notificacion_backlog_item_creacion_select_own
ON public.notificacion_backlog_item_creacion
FOR SELECT TO authenticated
USING (EXISTS (
  SELECT 1
  FROM public.notificacion n
  JOIN public.usuario u ON u.id = n.id_usuario
  WHERE n.id = public.notificacion_backlog_item_creacion.id_notificacion
    AND u.auth_id = auth.uid()
));

DROP POLICY IF EXISTS notificacion_sprint_vencimiento_select_own ON public.notificacion_sprint_vencimiento;
CREATE POLICY notificacion_sprint_vencimiento_select_own
ON public.notificacion_sprint_vencimiento
FOR SELECT TO authenticated
USING (EXISTS (
  SELECT 1
  FROM public.notificacion n
  JOIN public.usuario u ON u.id = n.id_usuario
  WHERE n.id = public.notificacion_sprint_vencimiento.id_notificacion
    AND u.auth_id = auth.uid()
));

-- Grants mínimos para uso desde Supabase
REVOKE ALL ON TABLE public.notificacion FROM anon, authenticated;
REVOKE ALL ON TABLE public.notificacion_invitacion_proyecto FROM anon, authenticated;
REVOKE ALL ON TABLE public.notificacion_proyecto FROM anon, authenticated;
REVOKE ALL ON TABLE public.notificacion_backlog_item_sugerencia FROM anon, authenticated;
REVOKE ALL ON TABLE public.notificacion_backlog_item_vencimiento FROM anon, authenticated;
REVOKE ALL ON TABLE public.notificacion_backlog_item_cambio FROM anon, authenticated;
REVOKE ALL ON TABLE public.notificacion_backlog_item_creacion FROM anon, authenticated;
REVOKE ALL ON TABLE public.notificacion_sprint_vencimiento FROM anon, authenticated;
REVOKE ALL ON TABLE public.notificacion_backlog_item_vencimiento_registro FROM anon, authenticated;
REVOKE ALL ON TABLE public.notificacion_sprint_vencimiento_registro FROM anon, authenticated;
REVOKE ALL ON TABLE public.notificacion_feed_view FROM anon, authenticated;
REVOKE ALL ON TABLE public.catalogo_tipo_notificacion FROM anon, authenticated;
REVOKE ALL ON TABLE public.catalogo_seccion_proyecto_notificacion FROM anon, authenticated;

GRANT SELECT ON TABLE public.catalogo_tipo_notificacion TO authenticated;
GRANT SELECT ON TABLE public.catalogo_seccion_proyecto_notificacion TO authenticated;
GRANT SELECT, DELETE ON TABLE public.notificacion TO authenticated;
GRANT UPDATE (leida, fecha_lectura) ON TABLE public.notificacion TO authenticated;
GRANT SELECT ON TABLE public.notificacion_invitacion_proyecto TO authenticated;
GRANT SELECT ON TABLE public.notificacion_proyecto TO authenticated;
GRANT SELECT ON TABLE public.notificacion_backlog_item_sugerencia TO authenticated;
GRANT SELECT ON TABLE public.notificacion_backlog_item_vencimiento TO authenticated;
GRANT SELECT ON TABLE public.notificacion_backlog_item_cambio TO authenticated;
GRANT SELECT ON TABLE public.notificacion_backlog_item_creacion TO authenticated;
GRANT SELECT ON TABLE public.notificacion_sprint_vencimiento TO authenticated;
GRANT SELECT ON TABLE public.notificacion_feed_view TO authenticated;

GRANT ALL ON TABLE public.notificacion TO service_role;
GRANT ALL ON TABLE public.notificacion_invitacion_proyecto TO service_role;
GRANT ALL ON TABLE public.notificacion_proyecto TO service_role;
GRANT ALL ON TABLE public.notificacion_backlog_item_sugerencia TO service_role;
GRANT ALL ON TABLE public.notificacion_backlog_item_vencimiento TO service_role;
GRANT ALL ON TABLE public.notificacion_backlog_item_cambio TO service_role;
GRANT ALL ON TABLE public.notificacion_backlog_item_creacion TO service_role;
GRANT ALL ON TABLE public.notificacion_sprint_vencimiento TO service_role;
GRANT ALL ON TABLE public.notificacion_backlog_item_vencimiento_registro TO service_role;
GRANT ALL ON TABLE public.notificacion_sprint_vencimiento_registro TO service_role;
GRANT ALL ON TABLE public.catalogo_tipo_notificacion TO service_role;
GRANT ALL ON TABLE public.catalogo_seccion_proyecto_notificacion TO service_role;
GRANT ALL ON TABLE public.notificacion_feed_view TO service_role;

DO $$
DECLARE
  v_seq text;
BEGIN
  v_seq := pg_get_serial_sequence('public.notificacion', 'id');
  IF v_seq IS NOT NULL THEN
    EXECUTE format('REVOKE ALL ON SEQUENCE %s FROM anon, authenticated', v_seq);
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO service_role', v_seq);
  END IF;
END $$;

REVOKE ALL ON FUNCTION public.obtener_id_tipo_notificacion(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.obtener_id_seccion_proyecto_notificacion(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.obtener_id_usuario_actual() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.crear_notificacion_base(integer, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.crear_notificaciones_proyecto(integer, character varying, character varying, character varying, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.crear_notificaciones_cambio_backlog_item(bigint, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.crear_notificacion_creacion_backlog_item(bigint) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.crear_notificaciones_sugerencia_backlog_item(bigint, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.crear_notificacion_invitacion_proyecto(integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.generar_notificaciones_backlog_items_proximos_vencer(integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.generar_notificaciones_sprints_proximos_vencer(integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.marcar_notificacion_como_leida(integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.marcar_notificacion_como_no_leida(integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.mark_notification_as_read(integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.mark_notification_as_unread(integer) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.marcar_notificacion_como_leida(integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.marcar_notificacion_como_no_leida(integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.mark_notification_as_read(integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.mark_notification_as_unread(integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.generar_notificaciones_backlog_items_proximos_vencer(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.generar_notificaciones_sprints_proximos_vencer(integer) TO service_role;

COMMIT;