BEGIN;

CREATE TABLE public.catalogo_tipo_notificacion (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar(50) NOT NULL UNIQUE,
  nombre varchar(80) NOT NULL,
  descripcion varchar(250),
  activo boolean NOT NULL DEFAULT true
);

INSERT INTO public.catalogo_tipo_notificacion
  (id, codigo, nombre, descripcion, activo)
VALUES
  (1, 'sistema', 'Sistema', 'Notificación general del sistema.', true),
  (2, 'invitacion_proyecto', 'Invitación a proyecto', 'Notificación asociada a una invitación para unirse a un proyecto.', true),
  (3, 'backlog_item_sugerencia', 'Sugerencia de backlog item', 'Notificación asociada a una sugerencia o propuesta de creación de backlog item.', true),
  (4, 'proyecto', 'Proyecto', 'Notificación general relacionada con un proyecto y una sección del proyecto.', true),
  (5, 'backlog_item_proximo_vencer', 'Backlog item próximo a vencer', 'Notificación automática para backlog items que vencen en las próximas 24 horas.', true)
ON CONFLICT (codigo) DO UPDATE
SET
  nombre = EXCLUDED.nombre,
  descripcion = EXCLUDED.descripcion,
  activo = EXCLUDED.activo;

CALL sync_all_id_sequences();

CREATE TABLE public.catalogo_seccion_proyecto_notificacion (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar(50) NOT NULL UNIQUE,
  nombre varchar(80) NOT NULL,
  ruta_relativa varchar(100) NOT NULL,
  activo boolean NOT NULL DEFAULT true
);

INSERT INTO public.catalogo_seccion_proyecto_notificacion
  (id, codigo, nombre, ruta_relativa, activo)
VALUES
  (1, 'resumen', 'Resumen', 'resumen', true),
  (2, 'backlog', 'Backlog', 'backlog', true),
  (3, 'sprints', 'Sprints', 'sprints', true),
  (4, 'hitos', 'Hitos', 'hitos', true),
  (5, 'equipo', 'Equipo', 'equipo', true),
  (6, 'check_ins', 'Check-ins', 'check-ins', true),
  (7, 'bitacora', 'Bitácora', 'bitacora', true),
  (8, 'configuracion', 'Configuración', 'configuracion', true)
ON CONFLICT (codigo) DO UPDATE
SET
  nombre = EXCLUDED.nombre,
  ruta_relativa = EXCLUDED.ruta_relativa,
  activo = EXCLUDED.activo;

CALL sync_all_id_sequences();

ALTER TABLE public.notificacion
  ADD COLUMN id_tipo_notificacion smallint;

UPDATE public.notificacion
SET id_tipo_notificacion = 1
WHERE id_tipo_notificacion IS NULL;

ALTER TABLE public.notificacion
  ALTER COLUMN id_tipo_notificacion SET DEFAULT 1;

ALTER TABLE public.notificacion
  ALTER COLUMN id_tipo_notificacion SET NOT NULL;

ALTER TABLE public.notificacion
  ADD CONSTRAINT notificacion_id_tipo_notificacion_fkey
  FOREIGN KEY (id_tipo_notificacion)
  REFERENCES public.catalogo_tipo_notificacion(id);

ALTER TABLE public.notificacion
  ADD CONSTRAINT notificacion_id_id_tipo_notificacion_key
  UNIQUE (id, id_tipo_notificacion);

CREATE INDEX idx_notificacion_usuario_fecha
ON public.notificacion (id_usuario, fecha_envio DESC, id DESC);

CREATE INDEX idx_notificacion_usuario_leida_fecha
ON public.notificacion (id_usuario, leida, fecha_envio DESC);

CREATE INDEX idx_notificacion_tipo
ON public.notificacion (id_tipo_notificacion);

ALTER TABLE public.backlog_item
  ADD CONSTRAINT backlog_item_id_id_proyecto_key
  UNIQUE (id, id_proyecto);

CREATE TABLE public.notificacion_invitacion_proyecto (
  id_notificacion integer PRIMARY KEY,
  id_tipo_notificacion smallint GENERATED ALWAYS AS (2::smallint) STORED,
  id_invitacion_proyecto integer NOT NULL,
  CONSTRAINT notificacion_invitacion_proyecto_tipo_fkey
    FOREIGN KEY (id_notificacion, id_tipo_notificacion)
    REFERENCES public.notificacion(id, id_tipo_notificacion)
    ON DELETE CASCADE,
  CONSTRAINT notificacion_invitacion_proyecto_invitacion_fkey
    FOREIGN KEY (id_invitacion_proyecto)
    REFERENCES public.invitacion_proyecto(id)
    ON DELETE RESTRICT
);

CREATE UNIQUE INDEX idx_notificacion_invitacion_proyecto_unique_invitacion
ON public.notificacion_invitacion_proyecto (id_invitacion_proyecto);

CREATE TABLE public.notificacion_backlog_item_sugerencia (
  id_notificacion integer PRIMARY KEY,
  id_tipo_notificacion smallint GENERATED ALWAYS AS (3::smallint) STORED,
  id_backlog_item bigint NOT NULL,
  CONSTRAINT notificacion_backlog_item_sugerencia_tipo_fkey
    FOREIGN KEY (id_notificacion, id_tipo_notificacion)
    REFERENCES public.notificacion(id, id_tipo_notificacion)
    ON DELETE CASCADE,
  CONSTRAINT notificacion_backlog_item_sugerencia_backlog_fkey
    FOREIGN KEY (id_backlog_item)
    REFERENCES public.backlog_item_sugerencia_creacion(id)
    ON DELETE RESTRICT
);

CREATE INDEX idx_notificacion_backlog_item_sugerencia_backlog
ON public.notificacion_backlog_item_sugerencia (id_backlog_item);

CREATE TABLE public.notificacion_proyecto (
  id_notificacion integer PRIMARY KEY,
  id_tipo_notificacion smallint GENERATED ALWAYS AS (4::smallint) STORED,
  id_proyecto integer NOT NULL,
  id_seccion_proyecto smallint NOT NULL,
  id_usuario_actor integer,
  CONSTRAINT notificacion_proyecto_tipo_fkey
    FOREIGN KEY (id_notificacion, id_tipo_notificacion)
    REFERENCES public.notificacion(id, id_tipo_notificacion)
    ON DELETE CASCADE,
  CONSTRAINT notificacion_proyecto_proyecto_fkey
    FOREIGN KEY (id_proyecto)
    REFERENCES public.proyecto(id)
    ON DELETE RESTRICT,
  CONSTRAINT notificacion_proyecto_seccion_fkey
    FOREIGN KEY (id_seccion_proyecto)
    REFERENCES public.catalogo_seccion_proyecto_notificacion(id),
  CONSTRAINT notificacion_proyecto_usuario_actor_fkey
    FOREIGN KEY (id_usuario_actor)
    REFERENCES public.usuario(id)
    ON DELETE SET NULL
);

CREATE INDEX idx_notificacion_proyecto_proyecto
ON public.notificacion_proyecto (id_proyecto);

CREATE INDEX idx_notificacion_proyecto_seccion
ON public.notificacion_proyecto (id_seccion_proyecto);

CREATE TABLE public.notificacion_backlog_item_vencimiento (
  id_notificacion integer PRIMARY KEY,
  id_tipo_notificacion smallint GENERATED ALWAYS AS (5::smallint) STORED,
  id_backlog_item bigint NOT NULL,
  id_proyecto integer NOT NULL,
  fecha_vencimiento_notificada timestamptz NOT NULL,
  CONSTRAINT notificacion_backlog_item_vencimiento_tipo_fkey
    FOREIGN KEY (id_notificacion, id_tipo_notificacion)
    REFERENCES public.notificacion(id, id_tipo_notificacion)
    ON DELETE CASCADE,
  CONSTRAINT notificacion_backlog_item_vencimiento_backlog_fkey
    FOREIGN KEY (id_backlog_item, id_proyecto)
    REFERENCES public.backlog_item(id, id_proyecto)
    ON DELETE RESTRICT,
  CONSTRAINT notificacion_backlog_item_vencimiento_proyecto_fkey
    FOREIGN KEY (id_proyecto)
    REFERENCES public.proyecto(id)
    ON DELETE RESTRICT
);

CREATE INDEX idx_notificacion_backlog_item_vencimiento_backlog
ON public.notificacion_backlog_item_vencimiento (id_backlog_item);

CREATE INDEX idx_notificacion_backlog_item_vencimiento_proyecto
ON public.notificacion_backlog_item_vencimiento (id_proyecto);

CREATE TABLE public.notificacion_backlog_item_vencimiento_registro (
  id_usuario integer NOT NULL,
  id_backlog_item bigint NOT NULL,
  fecha_vencimiento_notificada timestamptz NOT NULL,
  id_notificacion integer,
  fecha_registro timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_usuario, id_backlog_item, fecha_vencimiento_notificada),
  CONSTRAINT notificacion_backlog_item_vencimiento_registro_usuario_fkey
    FOREIGN KEY (id_usuario)
    REFERENCES public.usuario(id)
    ON DELETE CASCADE,
  CONSTRAINT notificacion_backlog_item_vencimiento_registro_backlog_fkey
    FOREIGN KEY (id_backlog_item)
    REFERENCES public.backlog_item(id)
    ON DELETE CASCADE,
  CONSTRAINT notificacion_backlog_item_vencimiento_registro_notificacion_fkey
    FOREIGN KEY (id_notificacion)
    REFERENCES public.notificacion(id)
    ON DELETE SET NULL
);

CREATE TABLE public.notificacion_sprint_vencimiento_registro (
  id_usuario integer NOT NULL,
  id_sprint bigint NOT NULL,
  fecha_final_notificada timestamptz NOT NULL,
  id_notificacion integer,
  fecha_registro timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id_usuario, id_sprint, fecha_final_notificada),
  CONSTRAINT notificacion_sprint_vencimiento_registro_usuario_fkey
    FOREIGN KEY (id_usuario)
    REFERENCES public.usuario(id)
    ON DELETE CASCADE,
  CONSTRAINT notificacion_sprint_vencimiento_registro_sprint_fkey
    FOREIGN KEY (id_sprint)
    REFERENCES public.sprint(id)
    ON DELETE CASCADE,
  CONSTRAINT notificacion_sprint_vencimiento_registro_notificacion_fkey
    FOREIGN KEY (id_notificacion)
    REFERENCES public.notificacion(id)
    ON DELETE SET NULL
);

ALTER TABLE public.catalogo_tipo_notificacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalogo_seccion_proyecto_notificacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_invitacion_proyecto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_backlog_item_sugerencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_proyecto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_backlog_item_vencimiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_backlog_item_vencimiento_registro ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion_sprint_vencimiento_registro ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS catalogo_tipo_notificacion_select_authenticated
ON public.catalogo_tipo_notificacion;

CREATE POLICY catalogo_tipo_notificacion_select_authenticated
ON public.catalogo_tipo_notificacion
FOR SELECT
TO authenticated
USING (activo = true);

DROP POLICY IF EXISTS catalogo_seccion_proyecto_notificacion_select_authenticated
ON public.catalogo_seccion_proyecto_notificacion;

CREATE POLICY catalogo_seccion_proyecto_notificacion_select_authenticated
ON public.catalogo_seccion_proyecto_notificacion
FOR SELECT
TO authenticated
USING (activo = true);

DROP POLICY IF EXISTS notificacion_invitacion_proyecto_select_own
ON public.notificacion_invitacion_proyecto;

CREATE POLICY notificacion_invitacion_proyecto_select_own
ON public.notificacion_invitacion_proyecto
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.notificacion n
    JOIN public.usuario u ON u.id = n.id_usuario
    WHERE n.id = notificacion_invitacion_proyecto.id_notificacion
      AND u.auth_id = auth.uid()
  )
);

DROP POLICY IF EXISTS notificacion_backlog_item_sugerencia_select_own
ON public.notificacion_backlog_item_sugerencia;

CREATE POLICY notificacion_backlog_item_sugerencia_select_own
ON public.notificacion_backlog_item_sugerencia
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.notificacion n
    JOIN public.usuario u ON u.id = n.id_usuario
    WHERE n.id = notificacion_backlog_item_sugerencia.id_notificacion
      AND u.auth_id = auth.uid()
  )
);

DROP POLICY IF EXISTS notificacion_proyecto_select_own
ON public.notificacion_proyecto;

CREATE POLICY notificacion_proyecto_select_own
ON public.notificacion_proyecto
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.notificacion n
    JOIN public.usuario u ON u.id = n.id_usuario
    WHERE n.id = notificacion_proyecto.id_notificacion
      AND u.auth_id = auth.uid()
  )
);

DROP POLICY IF EXISTS notificacion_backlog_item_vencimiento_select_own
ON public.notificacion_backlog_item_vencimiento;

CREATE POLICY notificacion_backlog_item_vencimiento_select_own
ON public.notificacion_backlog_item_vencimiento
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.notificacion n
    JOIN public.usuario u ON u.id = n.id_usuario
    WHERE n.id = notificacion_backlog_item_vencimiento.id_notificacion
      AND u.auth_id = auth.uid()
  )
);

ALTER TABLE public.suscripcion_notificacion_backlog_item ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS suscripcion_backlog_select_own
ON public.suscripcion_notificacion_backlog_item;

CREATE POLICY suscripcion_backlog_select_own
ON public.suscripcion_notificacion_backlog_item
FOR SELECT
TO authenticated
USING (
  id_usuario = (
    SELECT u.id
    FROM public.usuario u
    WHERE u.auth_id = auth.uid()
    LIMIT 1
  )
);

DROP POLICY IF EXISTS suscripcion_backlog_insert_own_with_project_access
ON public.suscripcion_notificacion_backlog_item;

CREATE POLICY suscripcion_backlog_insert_own_with_project_access
ON public.suscripcion_notificacion_backlog_item
FOR INSERT
TO authenticated
WITH CHECK (
  id_usuario = (
    SELECT u.id
    FROM public.usuario u
    WHERE u.auth_id = auth.uid()
    LIMIT 1
  )
  AND EXISTS (
    SELECT 1
    FROM public.backlog_item bi
    WHERE bi.id = suscripcion_notificacion_backlog_item.id_backlog_item
      AND (
        EXISTS (
          SELECT 1
          FROM public.usuario u
          WHERE u.auth_id = auth.uid()
            AND u.id_rol_global = ANY (ARRAY[1, 2])
        )
        OR EXISTS (
          SELECT 1
          FROM public.usuario_proyecto up
          JOIN public.usuario u
            ON u.id = up.id_usuario
          WHERE u.auth_id = auth.uid()
            AND up.id_proyecto = bi.id_proyecto
        )
      )
  )
);

DROP POLICY IF EXISTS suscripcion_backlog_delete_own
ON public.suscripcion_notificacion_backlog_item;

CREATE POLICY suscripcion_backlog_delete_own
ON public.suscripcion_notificacion_backlog_item
FOR DELETE
TO authenticated
USING (
  id_usuario = (
    SELECT u.id
    FROM public.usuario u
    WHERE u.auth_id = auth.uid()
    LIMIT 1
  )
);

CREATE INDEX idx_suscripcion_backlog_item
ON public.suscripcion_notificacion_backlog_item (id_backlog_item);

CREATE INDEX idx_suscripcion_usuario
ON public.suscripcion_notificacion_backlog_item (id_usuario);

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_de_invitacion()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
BEGIN
  DELETE FROM public.notificacion n
  USING public.notificacion_invitacion_proyecto nip
  WHERE nip.id_notificacion = n.id
    AND nip.id_invitacion_proyecto = OLD.id;

  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_de_invitacion
ON public.invitacion_proyecto;

CREATE TRIGGER trg_eliminar_notificaciones_de_invitacion
BEFORE DELETE
ON public.invitacion_proyecto
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_de_invitacion();

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_de_invitacion_aceptada()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
BEGIN
  IF NEW.aceptada = true AND OLD.aceptada IS DISTINCT FROM true THEN
    DELETE FROM public.notificacion n
    USING public.notificacion_invitacion_proyecto nip
    WHERE nip.id_notificacion = n.id
      AND nip.id_invitacion_proyecto = NEW.id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_de_invitacion_aceptada
ON public.invitacion_proyecto;

CREATE TRIGGER trg_eliminar_notificaciones_de_invitacion_aceptada
AFTER UPDATE OF aceptada
ON public.invitacion_proyecto
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_de_invitacion_aceptada();

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_de_sugerencia_aceptada()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
BEGIN
  IF NEW.aceptada = true AND OLD.aceptada IS DISTINCT FROM true THEN
    DELETE FROM public.notificacion n
    USING public.notificacion_backlog_item_sugerencia nbis
    WHERE nbis.id_notificacion = n.id
      AND nbis.id_backlog_item = NEW.id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_de_sugerencia_aceptada
ON public.backlog_item_sugerencia_creacion;

CREATE TRIGGER trg_eliminar_notificaciones_de_sugerencia_aceptada
AFTER UPDATE OF aceptada
ON public.backlog_item_sugerencia_creacion
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_de_sugerencia_aceptada();

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_de_sugerencia_borrada()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
BEGIN
  DELETE FROM public.notificacion n
  USING public.notificacion_backlog_item_sugerencia nbis
  WHERE nbis.id_notificacion = n.id
    AND nbis.id_backlog_item = OLD.id;

  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_de_sugerencia_borrada
ON public.backlog_item_sugerencia_creacion;

CREATE TRIGGER trg_eliminar_notificaciones_de_sugerencia_borrada
BEFORE DELETE
ON public.backlog_item_sugerencia_creacion
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_de_sugerencia_borrada();

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_de_proyecto()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
BEGIN
  DELETE FROM public.notificacion n
  USING public.notificacion_proyecto np
  WHERE np.id_notificacion = n.id
    AND np.id_proyecto = OLD.id;

  DELETE FROM public.notificacion n
  USING public.notificacion_backlog_item_vencimiento nbiv
  WHERE nbiv.id_notificacion = n.id
    AND nbiv.id_proyecto = OLD.id;

  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_de_proyecto
ON public.proyecto;

CREATE TRIGGER trg_eliminar_notificaciones_de_proyecto
BEFORE DELETE
ON public.proyecto
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_de_proyecto();

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_vencimiento_backlog_item()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
BEGIN
  DELETE FROM public.notificacion n
  USING public.notificacion_backlog_item_vencimiento nbiv
  WHERE nbiv.id_notificacion = n.id
    AND nbiv.id_backlog_item = OLD.id;

  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_vencimiento_backlog_item
ON public.backlog_item;

CREATE TRIGGER trg_eliminar_notificaciones_vencimiento_backlog_item
BEFORE DELETE
ON public.backlog_item
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_vencimiento_backlog_item();

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_vencimiento_backlog_item_resuelto()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
BEGIN
  IF NEW.es_terminal = true
     OR NEW.fecha_vencimiento IS DISTINCT FROM OLD.fecha_vencimiento THEN
    DELETE FROM public.notificacion n
    USING public.notificacion_backlog_item_vencimiento nbiv
    WHERE nbiv.id_notificacion = n.id
      AND nbiv.id_backlog_item = NEW.id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_vencimiento_backlog_item_resuelto
ON public.backlog_item;

CREATE TRIGGER trg_eliminar_notificaciones_vencimiento_backlog_item_resuelto
AFTER UPDATE OF es_terminal, fecha_vencimiento
ON public.backlog_item
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_vencimiento_backlog_item_resuelto();

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_vencimiento_sprint_resuelto()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
DECLARE
  v_es_terminal boolean;
BEGIN
  SELECT es.es_terminal
  INTO v_es_terminal
  FROM public.estatus_sprint es
  WHERE es.id = NEW.id_estatus;

  IF COALESCE(v_es_terminal, false) = true
     OR NEW.fecha_final IS DISTINCT FROM OLD.fecha_final THEN
    DELETE FROM public.notificacion n
    WHERE n.id IN (
      SELECT r.id_notificacion
      FROM public.notificacion_sprint_vencimiento_registro r
      WHERE r.id_sprint = NEW.id
        AND r.id_notificacion IS NOT NULL
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_vencimiento_sprint_resuelto
ON public.sprint;

CREATE TRIGGER trg_eliminar_notificaciones_vencimiento_sprint_resuelto
AFTER UPDATE OF id_estatus, fecha_final
ON public.sprint
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_vencimiento_sprint_resuelto();

CREATE OR REPLACE FUNCTION public.eliminar_notificaciones_vencimiento_sprint_borrado()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
BEGIN
  DELETE FROM public.notificacion n
  WHERE n.id IN (
    SELECT r.id_notificacion
    FROM public.notificacion_sprint_vencimiento_registro r
    WHERE r.id_sprint = OLD.id
      AND r.id_notificacion IS NOT NULL
  );

  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_eliminar_notificaciones_vencimiento_sprint_borrado
ON public.sprint;

CREATE TRIGGER trg_eliminar_notificaciones_vencimiento_sprint_borrado
BEFORE DELETE
ON public.sprint
FOR EACH ROW
EXECUTE FUNCTION public.eliminar_notificaciones_vencimiento_sprint_borrado();

CREATE OR REPLACE FUNCTION public.crear_notificacion_invitacion_proyecto(
  p_invitacion_id integer
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_user_id integer;
  v_inv public.invitacion_proyecto%ROWTYPE;
  v_id_notificacion integer;
BEGIN
  SELECT u.id
  INTO v_user_id
  FROM public.usuario u
  WHERE u.auth_id = auth.uid();

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado.'
      USING ERRCODE = '28000';
  END IF;

  SELECT *
  INTO v_inv
  FROM public.invitacion_proyecto
  WHERE id = p_invitacion_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invitación no encontrada.'
      USING ERRCODE = 'P0002';
  END IF;

  IF v_inv.aceptada = true THEN
    RAISE EXCEPTION 'No se puede notificar una invitación ya aceptada.'
      USING ERRCODE = '23514';
  END IF;

  IF NOT (
    v_inv.id_usuario_creador = v_user_id
    OR EXISTS (
      SELECT 1
      FROM public.usuario u
      WHERE u.id = v_user_id
        AND u.id_rol_global = ANY (ARRAY[1, 2])
    )
  ) THEN
    RAISE EXCEPTION 'No tienes permiso para crear la notificación de esta invitación.'
      USING ERRCODE = '42501';
  END IF;

  SELECT nip.id_notificacion
  INTO v_id_notificacion
  FROM public.notificacion_invitacion_proyecto nip
  WHERE nip.id_invitacion_proyecto = p_invitacion_id;

  IF v_id_notificacion IS NOT NULL THEN
    RETURN v_id_notificacion;
  END IF;

  INSERT INTO public.notificacion (
    nombre,
    descripcion,
    id_usuario,
    id_tipo_notificacion
  )
  VALUES (
    'Invitación a proyecto',
    LEFT(COALESCE(v_inv.descripcion, 'Tienes una nueva invitación a proyecto.'), 100),
    v_inv.id_usuario_destino,
    2
  )
  RETURNING id INTO v_id_notificacion;

  INSERT INTO public.notificacion_invitacion_proyecto (
    id_notificacion,
    id_invitacion_proyecto
  )
  VALUES (
    v_id_notificacion,
    p_invitacion_id
  );

  RETURN v_id_notificacion;
END;
$$;

CREATE OR REPLACE FUNCTION public.crear_notificaciones_sugerencia_backlog_item(
  p_id_backlog_item bigint,
  p_id_usuario_actor integer DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_backlog public.backlog_item%ROWTYPE;
  v_id_backlog_item_suscrito bigint;
  v_id_notificacion integer;
  v_total integer := 0;
  v_recipient record;
BEGIN
  SELECT bi.*
  INTO v_backlog
  FROM public.backlog_item bi
  JOIN public.backlog_item_sugerencia_creacion bis
    ON bis.id = bi.id
  WHERE bi.id = p_id_backlog_item;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No existe sugerencia de backlog item con id %.', p_id_backlog_item
      USING ERRCODE = 'P0002';
  END IF;

  v_id_backlog_item_suscrito := COALESCE(
    v_backlog.id_backlog_item_padre,
    v_backlog.id
  );

  FOR v_recipient IN
    SELECT DISTINCT s.id_usuario
    FROM public.suscripcion_notificacion_backlog_item s
    JOIN public.usuario u
      ON u.id = s.id_usuario
    WHERE s.id_backlog_item = v_id_backlog_item_suscrito
      AND u.activo = true
      AND s.id_usuario IS DISTINCT FROM p_id_usuario_actor
  LOOP
    IF NOT EXISTS (
      SELECT 1
      FROM public.notificacion n
      JOIN public.notificacion_backlog_item_sugerencia nbis
        ON nbis.id_notificacion = n.id
      WHERE n.id_usuario = v_recipient.id_usuario
        AND nbis.id_backlog_item = p_id_backlog_item
    ) THEN
      INSERT INTO public.notificacion (
        nombre,
        descripcion,
        id_usuario,
        id_tipo_notificacion
      )
      VALUES (
        'Nueva sugerencia de backlog item',
        'Hay una sugerencia relacionada con un backlog item que sigues.',
        v_recipient.id_usuario,
        3
      )
      RETURNING id INTO v_id_notificacion;

      INSERT INTO public.notificacion_backlog_item_sugerencia (
        id_notificacion,
        id_backlog_item
      )
      VALUES (
        v_id_notificacion,
        p_id_backlog_item
      );

      v_total := v_total + 1;
    END IF;
  END LOOP;

  RETURN v_total;
END;
$$;

CREATE OR REPLACE FUNCTION public.crear_notificaciones_proyecto(
  p_id_proyecto integer,
  p_codigo_seccion varchar,
  p_nombre varchar,
  p_descripcion varchar DEFAULT NULL,
  p_id_usuario_actor integer DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_id_seccion smallint;
  v_id_notificacion integer;
  v_total integer := 0;
  v_recipient record;
BEGIN
  SELECT s.id
  INTO v_id_seccion
  FROM public.catalogo_seccion_proyecto_notificacion s
  WHERE s.codigo = p_codigo_seccion
    AND s.activo = true;

  IF v_id_seccion IS NULL THEN
    RAISE EXCEPTION 'Sección de proyecto inválida: %', p_codigo_seccion
      USING ERRCODE = '23503';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.proyecto p
    WHERE p.id = p_id_proyecto
  ) THEN
    RAISE EXCEPTION 'Proyecto no encontrado: %', p_id_proyecto
      USING ERRCODE = 'P0002';
  END IF;

  FOR v_recipient IN
    SELECT DISTINCT u.id AS id_usuario
    FROM public.usuario u
    JOIN public.usuario_proyecto up
      ON up.id_usuario = u.id
    WHERE up.id_proyecto = p_id_proyecto
      AND u.activo = true
      AND (
        p_id_usuario_actor IS NULL
        OR u.id IS DISTINCT FROM p_id_usuario_actor
      )
  LOOP
    INSERT INTO public.notificacion (
      nombre,
      descripcion,
      id_usuario,
      id_tipo_notificacion
    )
    VALUES (
      LEFT(COALESCE(NULLIF(p_nombre, ''), 'Actualización de proyecto'), 50),
      LEFT(p_descripcion, 100),
      v_recipient.id_usuario,
      4
    )
    RETURNING id INTO v_id_notificacion;

    INSERT INTO public.notificacion_proyecto (
      id_notificacion,
      id_proyecto,
      id_seccion_proyecto,
      id_usuario_actor
    )
    VALUES (
      v_id_notificacion,
      p_id_proyecto,
      v_id_seccion,
      p_id_usuario_actor
    );

    v_total := v_total + 1;
  END LOOP;

  RETURN v_total;
END;
$$;

CREATE OR REPLACE FUNCTION public.generar_notificaciones_backlog_items_proximos_vencer(
  p_horas_anticipacion integer DEFAULT 24
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_total integer := 0;
  v_id_notificacion integer;
  v_item record;
  v_recipient record;
BEGIN
  IF p_horas_anticipacion IS NULL OR p_horas_anticipacion <= 0 THEN
    RAISE EXCEPTION 'p_horas_anticipacion debe ser mayor a 0.'
      USING ERRCODE = '22023';
  END IF;

  FOR v_item IN
    SELECT
      bi.id,
      bi.nombre,
      bi.descripcion,
      bi.fecha_vencimiento,
      bi.id_proyecto,
      bi.id_usuario_responsable,
      p.nombre AS nombre_proyecto
    FROM public.backlog_item bi
    JOIN public.proyecto p
      ON p.id = bi.id_proyecto
    WHERE bi.fecha_vencimiento IS NOT NULL
      AND bi.fecha_vencimiento > now()
      AND bi.fecha_vencimiento <= now() + make_interval(hours => p_horas_anticipacion)
      AND bi.es_terminal = false
  LOOP
    FOR v_recipient IN
      SELECT DISTINCT x.id_usuario
      FROM (
        SELECT v_item.id_usuario_responsable AS id_usuario
        WHERE v_item.id_usuario_responsable IS NOT NULL

        UNION

        SELECT s.id_usuario
        FROM public.suscripcion_notificacion_backlog_item s
        WHERE s.id_backlog_item = v_item.id
      ) x
      JOIN public.usuario u
        ON u.id = x.id_usuario
      WHERE u.activo = true
        AND (
          EXISTS (
            SELECT 1
            FROM public.usuario_proyecto up
            WHERE up.id_usuario = x.id_usuario
              AND up.id_proyecto = v_item.id_proyecto
          )
          OR u.id_rol_global = ANY (ARRAY[1, 2])
        )
    LOOP
      INSERT INTO public.notificacion_backlog_item_vencimiento_registro (
        id_usuario,
        id_backlog_item,
        fecha_vencimiento_notificada
      )
      VALUES (
        v_recipient.id_usuario,
        v_item.id,
        v_item.fecha_vencimiento
      )
      ON CONFLICT DO NOTHING;

      IF FOUND THEN
        INSERT INTO public.notificacion (
          nombre,
          descripcion,
          id_usuario,
          id_tipo_notificacion
        )
        VALUES (
          'Backlog item por vencer',
          LEFT('"' || v_item.nombre || '" vence en las próximas ' || p_horas_anticipacion::text || ' horas.', 100),
          v_recipient.id_usuario,
          5
        )
        RETURNING id INTO v_id_notificacion;

        INSERT INTO public.notificacion_backlog_item_vencimiento (
          id_notificacion,
          id_backlog_item,
          id_proyecto,
          fecha_vencimiento_notificada
        )
        VALUES (
          v_id_notificacion,
          v_item.id,
          v_item.id_proyecto,
          v_item.fecha_vencimiento
        );

        UPDATE public.notificacion_backlog_item_vencimiento_registro
        SET id_notificacion = v_id_notificacion
        WHERE id_usuario = v_recipient.id_usuario
          AND id_backlog_item = v_item.id
          AND fecha_vencimiento_notificada = v_item.fecha_vencimiento;

        v_total := v_total + 1;
      END IF;
    END LOOP;
  END LOOP;

  RETURN v_total;
END;
$$;

CREATE OR REPLACE FUNCTION public.generar_notificaciones_sprints_proximos_vencer(
  p_horas_anticipacion integer DEFAULT 24
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
  v_total integer := 0;
  v_id_notificacion integer;
  v_sprint record;
  v_recipient record;
  v_id_seccion_sprints smallint;
BEGIN
  IF p_horas_anticipacion IS NULL OR p_horas_anticipacion <= 0 THEN
    RAISE EXCEPTION 'p_horas_anticipacion debe ser mayor a 0.'
      USING ERRCODE = '22023';
  END IF;

  SELECT s.id
  INTO v_id_seccion_sprints
  FROM public.catalogo_seccion_proyecto_notificacion s
  WHERE s.codigo = 'sprints'
    AND s.activo = true;

  IF v_id_seccion_sprints IS NULL THEN
    RAISE EXCEPTION 'No existe sección activa de proyecto con código sprints.'
      USING ERRCODE = '23503';
  END IF;

  FOR v_sprint IN
    SELECT
      s.id,
      s.nombre,
      s.objetivo,
      s.fecha_final,
      s.id_proyecto,
      p.nombre AS nombre_proyecto
    FROM public.sprint s
    JOIN public.proyecto p
      ON p.id = s.id_proyecto
    JOIN public.estatus_sprint es
      ON es.id = s.id_estatus
    WHERE s.fecha_final IS NOT NULL
      AND s.fecha_final > now()
      AND s.fecha_final <= now() + make_interval(hours => p_horas_anticipacion)
      AND es.es_terminal = false
  LOOP
    FOR v_recipient IN
      SELECT DISTINCT u.id AS id_usuario
      FROM public.usuario u
      JOIN public.usuario_proyecto up
        ON up.id_usuario = u.id
      WHERE up.id_proyecto = v_sprint.id_proyecto
        AND u.activo = true
    LOOP
      INSERT INTO public.notificacion_sprint_vencimiento_registro (
        id_usuario,
        id_sprint,
        fecha_final_notificada
      )
      VALUES (
        v_recipient.id_usuario,
        v_sprint.id,
        v_sprint.fecha_final
      )
      ON CONFLICT DO NOTHING;

      IF FOUND THEN
        INSERT INTO public.notificacion (
          nombre,
          descripcion,
          id_usuario,
          id_tipo_notificacion
        )
        VALUES (
          'Sprint por finalizar',
          LEFT('"' || v_sprint.nombre || '" finaliza en las próximas ' || p_horas_anticipacion::text || ' horas.', 100),
          v_recipient.id_usuario,
          4
        )
        RETURNING id INTO v_id_notificacion;

        INSERT INTO public.notificacion_proyecto (
          id_notificacion,
          id_proyecto,
          id_seccion_proyecto,
          id_usuario_actor
        )
        VALUES (
          v_id_notificacion,
          v_sprint.id_proyecto,
          v_id_seccion_sprints,
          NULL
        );

        UPDATE public.notificacion_sprint_vencimiento_registro
        SET id_notificacion = v_id_notificacion
        WHERE id_usuario = v_recipient.id_usuario
          AND id_sprint = v_sprint.id
          AND fecha_final_notificada = v_sprint.fecha_final;

        v_total := v_total + 1;
      END IF;
    END LOOP;
  END LOOP;

  RETURN v_total;
END;
$$;

CREATE OR REPLACE VIEW public.notificacion_detalle_view
WITH (security_invoker = true)
AS
SELECT
  n.id,
  n.nombre,
  n.descripcion,
  n.leida,
  n.fecha_lectura,
  n.id_usuario,
  n.fecha_envio,
  n.id_tipo_notificacion,
  c.codigo AS tipo_codigo,
  c.nombre AS tipo_nombre,
  nip.id_invitacion_proyecto,
  ip.id_proyecto AS id_proyecto_invitacion,
  p_inv.nombre AS nombre_proyecto_invitacion,
  ip.id_usuario_creador AS id_usuario_creador_invitacion,
  ip.aceptada AS invitacion_aceptada,
  nbis.id_backlog_item AS id_backlog_item_sugerido,
  bi_sug.nombre AS nombre_backlog_item_sugerido,
  bi_sug.descripcion AS descripcion_backlog_item_sugerido,
  bi_sug.id_proyecto AS id_proyecto_backlog_item_sugerido,
  p_sug.nombre AS nombre_proyecto_backlog_item_sugerido,
  bis.aceptada AS sugerencia_aceptada,
  bis.id_usuario_acepto AS id_usuario_acepto_sugerencia,
  np.id_proyecto AS id_proyecto,
  p_np.nombre AS nombre_proyecto,
  np.id_seccion_proyecto,
  sp.codigo AS seccion_proyecto_codigo,
  sp.nombre AS seccion_proyecto_nombre,
  sp.ruta_relativa AS seccion_proyecto_ruta,
  np.id_usuario_actor AS id_usuario_actor_proyecto,
  nbiv.id_backlog_item AS id_backlog_item_por_vencer,
  bi_v.nombre AS nombre_backlog_item_por_vencer,
  bi_v.descripcion AS descripcion_backlog_item_por_vencer,
  nbiv.id_proyecto AS id_proyecto_backlog_item_por_vencer,
  p_v.nombre AS nombre_proyecto_backlog_item_por_vencer,
  nbiv.fecha_vencimiento_notificada,
  CASE
    WHEN c.codigo = 'invitacion_proyecto'
      THEN ip.id_proyecto
    WHEN c.codigo = 'backlog_item_sugerencia'
      THEN bi_sug.id_proyecto
    WHEN c.codigo = 'proyecto'
      THEN np.id_proyecto
    WHEN c.codigo = 'backlog_item_proximo_vencer'
      THEN nbiv.id_proyecto
    ELSE NULL
  END AS id_proyecto_destino,
  CASE
    WHEN c.codigo = 'invitacion_proyecto'
      THEN 'equipo'
    WHEN c.codigo = 'backlog_item_sugerencia'
      THEN 'backlog'
    WHEN c.codigo = 'proyecto'
      THEN sp.codigo
    WHEN c.codigo = 'backlog_item_proximo_vencer'
      THEN 'backlog'
    ELSE NULL
  END AS seccion_destino_codigo,
  CASE
    WHEN c.codigo = 'invitacion_proyecto'
      THEN 'equipo'
    WHEN c.codigo = 'backlog_item_sugerencia'
      THEN 'backlog'
    WHEN c.codigo = 'proyecto'
      THEN sp.ruta_relativa
    WHEN c.codigo = 'backlog_item_proximo_vencer'
      THEN 'backlog'
    ELSE NULL
  END AS seccion_destino_ruta
FROM public.notificacion n
JOIN public.catalogo_tipo_notificacion c
  ON c.id = n.id_tipo_notificacion
LEFT JOIN public.notificacion_invitacion_proyecto nip
  ON nip.id_notificacion = n.id
LEFT JOIN public.invitacion_proyecto ip
  ON ip.id = nip.id_invitacion_proyecto
LEFT JOIN public.proyecto p_inv
  ON p_inv.id = ip.id_proyecto
LEFT JOIN public.notificacion_backlog_item_sugerencia nbis
  ON nbis.id_notificacion = n.id
LEFT JOIN public.backlog_item_sugerencia_creacion bis
  ON bis.id = nbis.id_backlog_item
LEFT JOIN public.backlog_item bi_sug
  ON bi_sug.id = nbis.id_backlog_item
LEFT JOIN public.proyecto p_sug
  ON p_sug.id = bi_sug.id_proyecto
LEFT JOIN public.notificacion_proyecto np
  ON np.id_notificacion = n.id
LEFT JOIN public.proyecto p_np
  ON p_np.id = np.id_proyecto
LEFT JOIN public.catalogo_seccion_proyecto_notificacion sp
  ON sp.id = np.id_seccion_proyecto
LEFT JOIN public.notificacion_backlog_item_vencimiento nbiv
  ON nbiv.id_notificacion = n.id
LEFT JOIN public.backlog_item bi_v
  ON bi_v.id = nbiv.id_backlog_item
LEFT JOIN public.proyecto p_v
  ON p_v.id = nbiv.id_proyecto;

REVOKE ALL ON TABLE public.notificacion FROM anon;
GRANT SELECT, DELETE ON TABLE public.notificacion TO authenticated;
GRANT ALL ON TABLE public.notificacion TO service_role;

REVOKE ALL ON TABLE public.catalogo_tipo_notificacion FROM anon;
REVOKE ALL ON TABLE public.catalogo_seccion_proyecto_notificacion FROM anon;
REVOKE ALL ON TABLE public.notificacion_invitacion_proyecto FROM anon;
REVOKE ALL ON TABLE public.notificacion_backlog_item_sugerencia FROM anon;
REVOKE ALL ON TABLE public.notificacion_proyecto FROM anon;
REVOKE ALL ON TABLE public.notificacion_backlog_item_vencimiento FROM anon;
REVOKE ALL ON TABLE public.notificacion_backlog_item_vencimiento_registro FROM anon;
REVOKE ALL ON TABLE public.notificacion_sprint_vencimiento_registro FROM anon;
REVOKE ALL ON TABLE public.notificacion_detalle_view FROM anon;

GRANT SELECT ON TABLE public.catalogo_tipo_notificacion TO authenticated;
GRANT SELECT ON TABLE public.catalogo_seccion_proyecto_notificacion TO authenticated;
GRANT SELECT ON TABLE public.notificacion_invitacion_proyecto TO authenticated;
GRANT SELECT ON TABLE public.notificacion_backlog_item_sugerencia TO authenticated;
GRANT SELECT ON TABLE public.notificacion_proyecto TO authenticated;
GRANT SELECT ON TABLE public.notificacion_backlog_item_vencimiento TO authenticated;
GRANT SELECT ON TABLE public.notificacion_detalle_view TO authenticated;

GRANT ALL ON TABLE public.catalogo_tipo_notificacion TO service_role;
GRANT ALL ON TABLE public.catalogo_seccion_proyecto_notificacion TO service_role;
GRANT ALL ON TABLE public.notificacion_invitacion_proyecto TO service_role;
GRANT ALL ON TABLE public.notificacion_backlog_item_sugerencia TO service_role;
GRANT ALL ON TABLE public.notificacion_proyecto TO service_role;
GRANT ALL ON TABLE public.notificacion_backlog_item_vencimiento TO service_role;
GRANT ALL ON TABLE public.notificacion_backlog_item_vencimiento_registro TO service_role;
GRANT ALL ON TABLE public.notificacion_sprint_vencimiento_registro TO service_role;
GRANT ALL ON TABLE public.notificacion_detalle_view TO service_role;

REVOKE ALL ON TABLE public.suscripcion_notificacion_backlog_item FROM anon;

GRANT SELECT, INSERT, DELETE
ON TABLE public.suscripcion_notificacion_backlog_item
TO authenticated;

GRANT ALL
ON TABLE public.suscripcion_notificacion_backlog_item
TO service_role;

REVOKE ALL ON FUNCTION public.crear_notificacion_invitacion_proyecto(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.crear_notificaciones_sugerencia_backlog_item(bigint, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.crear_notificaciones_proyecto(integer, varchar, varchar, varchar, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.generar_notificaciones_backlog_items_proximos_vencer(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.generar_notificaciones_sprints_proximos_vencer(integer) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.crear_notificacion_invitacion_proyecto(integer)
TO authenticated, service_role;

GRANT EXECUTE ON FUNCTION public.crear_notificaciones_sugerencia_backlog_item(bigint, integer)
TO service_role;

GRANT EXECUTE ON FUNCTION public.crear_notificaciones_proyecto(integer, varchar, varchar, varchar, integer)
TO service_role;

GRANT EXECUTE ON FUNCTION public.generar_notificaciones_backlog_items_proximos_vencer(integer)
TO service_role;

GRANT EXECUTE ON FUNCTION public.generar_notificaciones_sprints_proximos_vencer(integer)
TO service_role;

REVOKE ALL ON FUNCTION public.eliminar_notificaciones_de_invitacion() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.eliminar_notificaciones_de_invitacion_aceptada() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.eliminar_notificaciones_de_sugerencia_aceptada() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.eliminar_notificaciones_de_sugerencia_borrada() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.eliminar_notificaciones_de_proyecto() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.eliminar_notificaciones_vencimiento_backlog_item() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.eliminar_notificaciones_vencimiento_backlog_item_resuelto() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.eliminar_notificaciones_vencimiento_sprint_resuelto() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.eliminar_notificaciones_vencimiento_sprint_borrado() FROM PUBLIC;

COMMIT;